const ETAPPEN = [{
        "nr": "Etappennummer",
        "titel": "Titel",
        "text": "Kurztext",
        "info": "Streckenbeschreibung",
        "start": "Ausgangspunkt",
        "ziel": "Endpunkt",
        "auf": "Hˆhenmeter bergauf",
        "ab": "Hˆhenmeter bergab",
        "hp": "Hˆchster Punkt",
        "grad": "Schwierigkeitsgrad",
        "km": "Streckenl‰nge (in km)",
        "stunden": "Gehzeit (in Stunden)",
        "einkehr": "Einkehrmˆglichkeiten",
        "track": "ID in GPS-Track"
    },
    {
        "nr": "1",
        "titel": "Adlerweg-Etappe 1: St. Johann ñ Gaudeamush¸tte",
        "text": "Die erste Etappe am Adlerweg f¸hrt vom St. Johanner Ortsteil Hinterkaiser zur Gaudeamush¸tte auf 1.263 Metern Seehˆhe. Zei besondere Naturschauspiele entlang der Strecke sind der imposante Schleierwasserfall und die Hˆhle Diebsˆfen.",
        "info": "Start im Ortszentrum von St. Johann in Tirol beim Tourismusb¸ro (ca. 250 Meter von Bahnhof entfernt). Wer mit dem Auto anreist hat die Mˆglichkeit auf dem ˆffentlichen Parkplatz (kostenlos) bei Koasastadion zu parken (ca. 400 Meter vom Tourismusb¸ro entfernt). Vom Tourismusb¸ro ausgehend geht man geradeaus Richtung Kreisverkehr zur Hauptstraﬂe, dort biegt man bei der groﬂen Hinweistafel Hinterkaiser ab und geht auf dem Hinterkaiserweg weiter in Richtung Rummlerhof. Vom Rummlerhof (Bauernhof mit angeschlossenem Wirtshaus) im St. Johanner Ortsteil Hinterkaiser auf schmalem, asphaltierten Fahrweg nach Westen Richtung ÑHaus Maurerhofì. Bald darauf der Beschilderung ÑSchleierwasserfallì folgen. Links am (Bauern-)Haus Nr. 80 vorbei (ÑWasserfall, Nr.33ì). Nun auf Weg bzw. Steig in den Wald und m‰ﬂig steil aufw‰rts. Es wird eine Forststraﬂe ¸berquert, jenseits der Forststraﬂe dem Steig mit der rot-weiﬂen Markierung folgen und den Bach entlang nach oben. Der Steig m¸ndet in einen Forstweg ñ hier links und wenig sp‰ter wieder rechts Richtung ÑSchleierwasserfallì halten (bis zum Schleierwasserfall stets auf dem Weg Nr. 33 bleiben). Weiter durch den Wald und ¸ber den Steig (eine seilversicherte Stelle) nach Diebsˆfen. Hier rinnt ein Bach unter einer Felswand vorbei, in der sich eine Hˆhle befindet. Hinunter ins Bachbett und den Markierungen in der Hˆhle folgen (Steig f¸hrt durch die Hˆhle durch). Von Diebsˆfen auf dem Steig hin¸ber bzw. gem¸tlich nach oben zum Schleierwasser-fall (ÑZwickstelle Wasserfallì): Hier geht man zwischen Wasserfall und Felswand. Von hier auf dem Steig Richtung ÑObere Regalmì und ansteigend an Kletterw‰nden vorbei. Sp‰ter vorbei an einem weiteren Wasserfall und ¸ber eine Wiese hinunter zu einer Steiggabelung ñ jetzt rechter Hand wieder nach oben (Nr. 817). Anschlieﬂend an ÑRegalmì bzw. ÑGaudeamush¸tteì orientieren. Der Steig verl‰uft in dem Bereich im freien Almgebiet, in Folge erneut abw‰rts und sp‰ter als Fahrweg hin¸ber zur Oberen Regalm (ÑZwickstelle Regalmì). Oberhalb der H¸tte Richtung ÑGaudeamush¸tteì und auf dem Steig im freien Gel‰nde z¸gig empor auf ein Joch (unmittelbar daneben Bergsteigergrab am Brennenden Palven). Jenseits des Sattels hinunter Richtung ÑGaudeamush¸tteì. Der Steig leitet sp‰ter unmittelbar vorbei an der Freibergh¸tte und recht z¸gig hinab zur Gaudeamush¸tte (Weg Nr. 35 ab dem Sattel).",
        "start": "Rummlerhof",
        "ziel": "Gaudeamush¸tte",
        "auf": "1060",
        "ab": "470",
        "hp": "1572",
        "grad": "mittelschwierig",
        "km": "9",
        "stunden": "5,5",
        "einkehr": "Rummlerhof#Obere Regalm#Gaudeamush¸tte",
        "track": "A01"
    },
    {
        "nr": "2",
        "titel": "Adlerweg-Etappe 2: Gaudeamush¸tte ñ Hintersteiner See",
        "text": "Diese Etappe f¸hrt ausgehend von der Gaudeamush¸tte ¸ber den Klammlweg zu einem besonderem Ziel entlang des Adlerwegs: dem Hintersteiner See. Der Bergsee lockt vor allem im Hochsommer mit Badefreuden.",
        "info": "Von der Gaudeamush¸tte ¸berwindet man ¸ber den Klammlweg fast 400 Hˆhenmeter bis zur Gruttenh¸tte, der hˆchstgelegenen H¸tte im Kaisergebiet. Dazu h‰lt man sich zuerst in Richtung Ellmauer Tor und biegt dann Richtung Westen auf den Steig Nr. 824, 813. Der Weg f¸hrt durch Wiesen und Latschen, nach der Querung eines trockenen Bachbettes gelangt man zum Wegweiser ÑGruttenh¸tte ¸ber Klammlì (Schwindelfreiheit und Trittsicherheit erforderlich). Der Weg verl‰uft ¸ber Steine und kleine Felsbrocken am Rand eines Gerˆlltrichters. Die Gaudeamush¸tte liegt jetzt schon deutlich unterhalb. Bald f¸hrt der schmale Weg um einen Felsen herum und man steht vor einer ca. zwei Meter langen Eisenleiter. Diese klettert man hinauf, dann geht es an einer Eisenkette entlang ¸ber einige Stufen. Links unten das Gerˆll, rechts die hohen Felsen, f¸hrt der Weg nun leicht bergan. Nach der Querung eines Gerˆllfeldes sieht man bald die Holzstufen zum Klamml-Eingang. Rechts von der Wand des Gruttenkopfs geht es steil nach oben. Der Weg ist mit Eisenklammern f¸r Tritte und Griffe gesichert. Bei der letzten Stufe zieht man sich ¸ber einen Felsen hoch. Am Ausstieg des Klamml links halten. Neben dem schmalen Weg f‰llt das Gel‰nde rechts steil ab, aber wenige Kehren sp‰ter erreicht man die Kuppe, von wo ein fast ebener Weg noch ein kurzes St¸ck zur Gruttenh¸tte f¸hrt. Gleich darauf m¸ndet von rechts der Weg vom Jubil‰umssteig ein. Von der Gruttenh¸tte (1.620 Meter) nimmt man den Gruttenweg 14 a Richtung S¸dwesten.† Auf rund 1.400 Meter Hˆhe zweigt vom Gruttenweg im Bereich vom Krummbachegg der ÑHˆhenwegì Nr. 823 Richtung Westen ab (Hintersteiner See). Jetzt auf dem Hˆhenweg, der auch ÑWilder-Kaiser-Steigì genannt wird, im lichten Mischwald sowie durch Latschen und Kare s¸dlich am Treffauer vorbei und um ihn herum marschieren, anschlieﬂend weiter Richtung ÑKaiser Hochalmì (unbewirtschaftet). Diese liegt auf 1.417 Meter im freien Gel‰nde, von hier aus geht es auf markiertem Weg hinunter. Nun an der Beschilderung ÑSteiner Hochalmì orientieren und dem Steig Nr. 823 folgen, der Steig verl‰uft durch Mischwald bergab. Am Waldrand gabelt sich die Route, an dieser Stelle rechts nach oben und dann gleich dem markierten Steig folgen, der links den Hang entlang zieht. Er f¸hrt zur Steiner Hochalm, wo man sich mit Getr‰nken erfrischen und musikalisch erfreuen kann, denn hier gibt es oft Harfenspiel und Gesang. S¸dˆstlich vom  Almgeb‰ude geht es ¸ber einen Karrenweg hinab zum ÑHintersteiner Seeì. Bald ˆffnet sich der Blick auf dieses schˆne Naturjuwel. Sp‰ter weiter auf einem Forstweg und dabei immer abw‰rts halten. Beim Gasthof B‰rnstatt bzw. bei der B‰rnstatt- Kapelle m¸ndet der Weg in die Fahrstraﬂe zum Hintersteiner See, hier geht es entlang der Straﬂe rechter Hand weiter an Blumenwiesen und H‰usern vorbei zum Ostufer des Sees. Auf dieser Etappe gibt es auﬂer auf der Gaudeamus- bzw. Gruttenh¸tte zu Etappenbeginn und gegen Etappenende (B‰rnstatt und am Hintersteiner See) keine Einkehrmˆglichkeit mit Mahlzeiten.",
        "start": "Gaudeamush¸tte",
        "ziel": "Hintersteiner See",
        "auf": "800",
        "ab": "1130",
        "hp": "1630",
        "grad": "mittelschwierig",
        "km": "14,5",
        "stunden": "6",
        "einkehr": "Gaudeamush¸tte#Gruttenh¸tte#Seest¸berl#Pension Maier",
        "track": "A02"
    },
    {
        "nr": "3",
        "titel": "Adlerweg-Etappe 3: Hintersteiner See ñ Kufstein",
        "text": "Die dritte Etappe am Adlerweg f¸hrt vom Hintersteiner See ins St‰dtchen Kufstein. Vom 1.470 Meter hohen Hochegg f¸hrt die sanfte Wanderung abw‰rts in Richtung Kufstein, wo man die imposante Festung Kufstein besichtigen kann.",
        "info": "Am Parkplatz vor dem Eingang zum Strandbad den Seeweg (Nr. 822) nehmen und entlang des S¸dufers bis zum  ÑBiobauernhof Pension Maierì wandern. Rechts am Bauernhof vorbei und beim Parkplatz Richtung Norden, wo der breite Wanderweg (ein privater Almzufahrtsweg) beginnt, der zur Walleralm f¸hrt. Auf diesem Weg (Nr. 45) bleibt man bis zur Walleralm, wobei man haupts‰chlich in nˆrdlicher Richtung u. a. links am Schafberg vorbei zuerst durch den Wald und sp‰ter durch freies Gel‰nde wandert, bis man schlieﬂlich ins Almgebiet gelangt. Auf der Walleralm mit dem Alpengasthaus Walleralm kann man einen beschaulichen Zwischenstopp einlegen. Dahinter beginnt der beschilderte Steig zur Kaindlh¸tte. Auf dem Steig groﬂteils im bewaldeten Gebiet gem¸tlich empor zum Hochegg (1.470 Meter). Kurz vor dem Hochegg-Buckel nimmt die Steigung noch einmal deutlich zu. Auf der grasigen Kuppe, beim Gipfelkreuz des Hochegg, lohnt sich eine Pause mit Blick auf das Inntal und den Zahmen Kaiser. Nun geht es sanft weiter durch freie Fl‰chen hinunter ins Almdorf der Steinbergalm mit der Kaindlh¸tte. Von der H¸tte dem Forstweg hinunter folgen, der zun‰chst durch Almgebiet f¸hrt und in einem Bogen um die (geschlossene) Steinbergh¸tte leitet. Die Forststraﬂe legt einen kleinen Gegenanstieg zum Brentenjoch ein, wo linker Hand der ausgeschilderte, markierte Weg zum Lift abzweigt. Nun noch ein paar weitere Meter hinauf zur Liftstation. Mit der Sesselbahn Wilder Kaiser schwebt man anschlieﬂend bequem und aussichtsreich ¸ber zwei Sektionen hinunter in den Kufsteiner Ortsteil Sparchen. Variante: Zu Fuﬂ besteht die Mˆglichkeit, ¸ber Aschenbrenner am Panoramaweg nach Kufstein zu gelangen.",
        "start": "Hintersteiner See",
        "ziel": "Kufstein",
        "auf": "730",
        "ab": "460",
        "hp": "1463",
        "grad": "mittelschwierig",
        "km": "9,5",
        "stunden": "3,5",
        "einkehr": "Seest¸berl#Pension Maier#Stˆfflh¸tte#Walleralm#Kaindlh¸tte#Gasthof Weinbergerhaus",
        "track": "A03"
    },
    {
        "nr": "4",
        "titel": "Adlerweg-Etappe 4: Kufstein ñ  Alpengasthof Buchacker",
        "text": "Nicht ganz ohne Schweiﬂ sind die mehr als 1.300 Hˆhenmeter dieser Adlerweg-Etappe zu bew‰ltigen. Aber es lohnt sich! Am Ende der Strecke wartet ein besonderes Naturschauspiel: die Hundsalm-Eishˆhle, eine auf knapp 1.400 Meter liegende Eis- und Tropfsteinhˆhle.",
        "info": "In Unterlangkampfen angelangt, rechts abbiegen, durch die Unterf¸hrung, dem Weg folgend bis ins Dorf zur Kirche. Oberhalb der Kirche der Hinweistafel ÑHˆhlensteinhausì folgen. Zun‰chst auf dem Forstweg Richtung ÑHˆhlensteinhausì. Bald rechts auf einen Karrenweg abzweigen. Die Route verl‰uft in der Folge recht steil auf einem Steig durch den Wald. Der Steig f¸hrt knapp vor dem Ziel auf eine freie Almwiese, wo sich in einer Senke das Hˆhlensteinhaus befindet. Unmittelbar beim Hˆhlensteinhaus f¸hrt ein Steig weiter Richtung ÑKˆglhˆrndlì (1.645 Meter). Die Route verl‰uft nun auf seinem sehr urt¸mlichen und steilen Steig durch den Wald in romantischer und einsamer Gegend nach oben auf den Kamm und ¸ber den Kamm bis zum Kˆglhˆrndl (1.645 Meter) mit dem Kreuz. Der Steig leitet dann wieder in den Wald hinunter. Die Route verl‰uft in Folge ab- und ansteigend und wieder nach oben zum Hundsalmjoch (1.637 Meter) mit dem modernen Hundsalmkreuz. Jetzt wird der Kamm verlassen, die Route f¸hrt direkt gegen¸ber vom Hundsalmkreuz auf markiertem Steig hinunter ins Almgel‰nde. Durch Wiesen geht es dann auf einer Abk¸rzung linker Hand hin¸ber zum Forstweg, ¸ber den der Schlussabstieg zum Alpengasthaus Buchacker erfolgt. Kurz vorher zweigt rechter Hand der Weg zur Hundsalm Eishˆhle ab (20 Minuten)",
        "start": "Kufstein",
        "ziel": "Alpengasthaus Buchacker",
        "auf": "1330",
        "ab": "500",
        "hp": "1617",
        "grad": "mittelschwierig",
        "km": "11",
        "stunden": "5,5",
        "einkehr": "Hˆhlensteinhaus#Gasthof Buchhacker",
        "track": "A04"
    },
    {
        "nr": "5",
        "titel": "Adlerweg-Etappe 5: Alpengasthof Buchacker ñ Kaiserhaus",
        "text": "Moderate Anspr¸che an die Kondition stellt diese Adlerweg-Etappe, die vom Alpengasthaus Buchacker zum Gasthof Gwerchtwirt f¸hrt. Entlang der Strecke gibt es immer wieder wunderbare Ausblicke zum Kaisergebirge, zu den Kitzb¸hler Alpen, zum Rofangebirge, zu den Zillertaler und Stubaier Alpen, und bei guter Sicht sogar bis zum Groﬂglockner und Groﬂvenediger.",
        "info": "Vom Gasthof Buchacker ein St¸ck den Forstweg bergab bis zur n‰chsten Kreuzung, hier rechts dem Wegverlauf folgen bis ins ÑHasatal\". Dann weiter zur n‰chsten Kreuzung, hier links etwas ansteigend und dann bald rechts auf den Steig in Richtung ÑNachbergalmen\" abzweigen. Nun geht es etwas steiler bergauf bis zum Nachberg Hochleger und weiter ¸ber das Almgebiet bis zum ÑAscherjoch\" auf 1.458 Meter. Jetzt kommt der technisch anspruchsvollere Teil der Tour ñ der Weg hinauf zum ÑPlessenberg\", ein schwarzer Bergweg mit vier Seilpassagen. Teilweise steigt man dabei recht steil aufw‰rts ¸ber Steintreppen und seilversicherte Stellen bis zum Gipfel auf 1.743 Meter. Von hier aus genieﬂt man eine herrliche Aussicht†zum Kaisergebirge, zu den Kitzb¸hler Alpen, zum Rofangebirge, zu den Zillertaler und Stubaier Alpen, bei guter Sicht sieht man sogar bis zum Groﬂglockner und Groﬂvenediger. Nach der verdienten Rast geht es kurz abw‰rts†bis zum Heubergsattel, hier rechts†in Richtung Kienberg halten. Der nachfolgende Aufstieg f¸hrt durch Latschenfelder zum Gipfel vom Kienberg und damit zur hˆchsten Erhebung der Tour auf 1.786 Meter. Damit ist das Aufstiegspensum erf¸llt. Ab jetzt geht es nur noch abw‰rts ¸ber schˆne Almgebiete, man passiert u.a. die Einkehralm und die Heubrandalm. Der Endspurt erfolgt ¸ber einen steilen Steig von ÑPrama\" hinunter nach Pinegg, wo man sich nach dieser langen und fordernden Etappe im Gasthaus Gwercherwirt ausruhen kann, das inmitten unber¸hrter Natur im Hochtal Brandenberg liegt.",
        "start": "Alpengasthaus Buchacker",
        "ziel": "Gasthof Gwercherwirt",
        "auf": "980",
        "ab": "1630",
        "hp": "1772",
        "grad": "leicht",
        "km": "18",
        "stunden": "3",
        "einkehr": "Gasthof Buchhacker#Gwercherwirt",
        "track": "A05"
    },
    {
        "nr": "6",
        "titel": "Adlerweg-Etappe 6: Kaiserhaus ñ Steinberg am Rofan",
        "text": "Gem¸tlich und dennoch lohnend ist die leichte Wanderung auf dieser Adlerweg-Etappe vom Gasthof Gwerchtwirt zum Gasthof Waldh‰usl in Steinberg am Rofan. ",
        "info": "Von Pinegg geht es ¸ber zwei Br¸cken ñ der Brandenberger Ache und danach der Steinberger Ache ñ zum ersten Anstieg dieser Etappe. Er verl‰uft vorerst ¸ber einen Wanderweg, dann ¸ber die Forststraﬂe zum J‰gersteig der nach Aschau, einem Ortsteil von Brandenberg, f¸hrt. Man durchwandert das kleine Dorfzentrum auf der Hauptstraﬂe bis kurz vor dem Gasthaus Haaser. Von hier aus geht es den Burgstallgraben hinauf bis zum letzten Bauernhof ÑWimm\". Nach dem Weiderost rechts und weiter der Beschilderung folgen bis zum Wimmerjoch. Hier, am hˆchsten Punkt der Etappe, lohnt es sich, auf den gr¸nen Almwiesen eine kleine Pause einzulegen. Anschlieﬂend links halten und abw‰rts in Richtung Lahnalm wandern. Kurz vor der Alm der Beschilderung zum Weiﬂenbachgraben folgen. Sobald man den Weiﬂenbach, den Grenzbach zwischen Brandenberg und Steinberg, ¸berquert hat, ist es nur noch ein kurzer Weg zum Enterhof, einem stattlichen Bauernhaus mit ‹bernachtungsmˆglichkeit. Diesen l‰sst man Ñlinks liegenì und folgt der Straﬂe hinunter ins Steinberger Loch, wobei man zum zweiten Mal auf dieser Etappe die Steinberger Ache ¸berquert. Danach bei der ersten Mˆglichkeit rechts auf den Hinterbergweg einbiegen. Diesem in Richtung Norden bis nach Vordersteinberg folgen, die Straﬂe ¸berqueren und weiterwandern zum B‰renwaldweg. Nun nur noch diesem Weg folgen und den Ausklang des Wandertages in der idyllisch gelegenen Jausenstation Gasthof Waldh‰usl am westlichen Ortsrand von Steinberg genieﬂen. Eine bequeme ‹bernachtungsmˆglichkeit gibt es hier auch.",
        "start": "Gasthof Gwercherwirt",
        "ziel": "Gasthof Waldh‰usl",
        "auf": "1100",
        "ab": "780",
        "hp": "1327",
        "grad": "leicht",
        "km": "18",
        "stunden": "3,5",
        "einkehr": "Gwercherwirt#Gasthof Waldh‰usl",
        "track": "A06"
    },
    {
        "nr": "7",
        "titel": "Adlerweg-Etappe 7: Steinberg am Rofan ñ Erfurter H¸tte",
        "text": "Von Steinberg am Rofan f¸hrt diese anspruchsvolle Adlerweg-Etappe ¸ber fast 1.600 Hˆhenmeter zur Erfurter H¸tte. Die Route entlang des Rofangebirges ist landschaftlich ‰uﬂerst reizvoll: Auf der einen Seite haben die Berge steile Felsw‰nde, auf der anderen sind sie mit sanften Almmatten gepolstert.",
        "info": "Vom Gasthof Waldh‰usl ein paar Meter nach S¸dosten und dann gleich die Dorfstraﬂe nehmen, die links von der Hauptstraﬂe abzweigt. Nach einem kurzen St¸ck rechts abbiegen Richtung ÑDurrahofì. Auf der weitgehend verkehrsfreien Fahrstraﬂe gem¸tlich hinunter ins kleine Tal des M¸hlbachs, den Bach entlang und in der Folge ¸ber die Ache. Dann wieder gem¸tlich nach oben vorbei am Enterhof bis zum Durrahof. Ab hier orientiert man sich an der Beschilderung ÑRofanì und wandert auf einem Forstweg weiter. Sp‰ter folgt man der Beschilderung ÑZireiner Seeì bzw. ÑErfurter H¸tteì, die Strecke verl‰uft kaum sp¸rbar ansteigend durch lichten Wald und Wiesen. Nach einem Hof teilt sich der Weg ñ hier die obere Route nehmen und nicht hinunter gehen. Der Weg verwandelt sich gleich in einen Steig. Nach der ‹berquerung eines Bachs mit einem kleinen Wasserfall trifft der Steig auf einen Fahrweg ñ hier rechts auf dem Fahrweg Richtung ÑBayreuther H¸tteì. Bei der folgenden Weggabelung links hinauf und den Bach entlang nach oben. Sp‰ter ¸ber einen Steig zu einer breiten Forststraﬂe. Rechts weiter und gleich anschlieﬂend linker Hand den Fahrweg hinauf nehmen, der rasch zum Steig wird. Auf dem Steig im lichten Wald den Bach entlang Richtung ÑZireiner Seeì. Der Bach wird ¸berquert (keine Br¸cke), es geht nun steiler im Wald hinauf ins freie Almgel‰nde zur idyllische Schauertalalm. Anschlieﬂend auf dem Steig nach oben Richtung ÑSchauertalsattelì. Der nun recht steinige, mit Wurzeln ¸berwachsene Steig verl‰uft in dem Abschnitt direkt und z¸gig empor, vielfach durch Latschen. Man gelangt in einen Kessel ñ hier Richtung ÑErfurter H¸tteì und s¸dlich am Zireiner See vorbei. Nun an ÑMarchalmì orientieren, wenig sp‰ter Richtung ÑSchafsteig (Achtung bei N‰sse!), Rofanì. Der Schafsteig zieht die Rofanspitz-Ostwand entlang und dann schr‰g nach oben, ehe er durch steiles Gel‰nde zum Schafsteigsattel nordˆstlich der Rofanspitze leitet. Vom Sattel linker Hand im sanften Wiesengel‰nde ein kurzes St¸ck abw‰rts. Wenig sp‰ter der Beschilderung ÑErfurter H¸tteì bzw. ÑRofanseilbahnì folgen und auf dem Steig s¸dlich der Rofanspitze beinahe eben hin¸ber zum Joch. Der Steig leitet anschlieﬂend sanft hinab in ein gr¸nes Becken. Von hier weiter gem¸tlich im Almgel‰nde hinunter zur Erfurter H¸tte direkt neben der Bergstation der Rofanseilbahn. Kurz vor dem Ziel f¸hrt die Route noch an der Mauritzalm vorbei. Ab dem Schafsteigsattel folgt man stets der Beschilderung ÑErfurter H¸tteì bzw. ÑRofanseilbahnì. Von dort entweder zu Fuﬂ (ca. 1 Ω Std.) oder mit der Seilbahn nach Maurach. Nahezu die gesamte Strecke verl‰uft entlang des Nordalpenwegs 01.",
        "start": "Gasthof Waldh‰usl",
        "ziel": "Erfurter H¸tte",
        "auf": "1590",
        "ab": "770",
        "hp": "2192",
        "grad": "schwierig",
        "km": "18",
        "stunden": "7",
        "einkehr": "Gasthof Waldh‰usl#Erfurter H¸tte#Berggasthof Rofan#Mauritzalm",
        "track": "A07"
    },
    {
        "nr": "8",
        "titel": "Adlerweg-Etappe 8: Erfurter H¸tte ñ Lamsenjochh¸tte",
        "text": "Diese Etappe am Adlerweg beginnt entweder mit einer Seilbahnfahrt von der Erfurter H¸tte hinunter nach Maurach oder startet direkt in Maurach. Weiter f¸hrt die Route am Achensee entlang nach Pertisau und ins sanft ansteigende Falzthurntal bis zur Gramaialm.",
        "info": "Von der Erfurter H¸tte mit der Rofanseilbahn hinunter nach Maurach oder startet bereits in Maurach. Von dort auf dem Fuﬂweg das S¸d- bzw. S¸dwestufer des Achensees entlang nach Pertisau zum Beginn der Mautstraﬂe in die Karwendelt‰ler (in Pertisau an den Schildern ÑKarwendelt‰lerì orientieren). Unmittelbar nach der Mautstelle links der Beschilderung ÑGramaialmì ins Falzthurntal folgen. Jetzt auf einem breiten, asphaltierten Fuﬂweg im Wald kaum sp¸rbar ansteigend zur Falzthurnalm mit der Sennh¸tte Falzthurn und dem Alpengasthof Falzthurn. Hier endet der asphaltierte Abschnitt. Anschlieﬂend auf einem sanft ansteigenden Fuﬂweg ¸ber Wiesen weiter ins Tal hinein (nirgendwo links den Hang hinauf), hie und da das in der Regel ausgetrocknete Schotterbachbett ¸berquerend, bis zur Gramaialm. Von der Gramaialm zun‰chst auf dem Fahr- bzw. Karrenweg weiter taleinw‰rts Richtung ÑLamsenjochh¸tteì. Bald wird das meist ausgetrocknete Bachbett nach links ¸berquert. Die Route zieht durch den Talboden und vorbei an der Abzweigung zum Gramai-Hochleger. Ab hier verl‰uft die Etappe auf einem Steig. Es geht durch den Gramaier Grund und auf den steilen Hang im Talschluss (S¸den) zu, ¸ber dem rechts markant die Lamsenspitze aufragt. Der Steig leitet in der Folge ein kurzes St¸ck links den Hang empor, um anschlieﬂend taleinw‰rts Schuttreisen zu queren. Zum Schluss schraubt sich die Route in Serpentinen den zum Teil schottrigen und recht steilen Hang nach oben. Schlieﬂlich vom Joch in wenigen Schritten links hin¸ber zu der bereits sichtbaren Lamsenjochh¸tte.",
        "start": "Erfurter H¸tte",
        "ziel": "Lamsenjochh¸tte",
        "auf": "1030",
        "ab": "70",
        "hp": "1949",
        "grad": "mittelschwierig",
        "km": "17",
        "stunden": "2",
        "einkehr": "Erfurter H¸tte#Berggasthof Rofan#Mauritzalm#Falzthurnalm#Sennh¸tte #Gramaialm#Lamsenjochh¸tte",
        "track": "A08"
    },
    {
        "nr": "9",
        "titel": "Adlerweg-Etappe 9: Lamsenjochh¸tte ñ Falkenh¸tte",
        "text": "Diese Etappe am Adlerweg f¸hrt von der 1908 errichteten Lamsenjochh¸tte auf knapp 2.000 Metern zur Falkenh¸tte. Die Tour durchquert dabei den ÑGroﬂen Ahornbodenì, ein Naturdenkmal mit mehr als 2.000 Bergahornen.",
        "info": "Von der Lamsenjochh¸tte auf dem Steig ein paar Meter entlang der Aufstiegsroute zur¸ck, auf der Einsattelung jedoch Richtung ÑBinsalmì bzw. ÑFalkenh¸tteì. Der Steig leitet im absch¸ssigen Gel‰nde unter der Lamsenspitze hindurch sanft absteigend zum Westlichen Lamsenjoch (1.940 Meter). Auf der anderen Seite des Jochs auf dem Steig Richtung ÑBinsalpeì bzw. ÑEngì absteigen. Der Steig verwandelt sich bald in einen Karren- bzw. Fahrweg. Die Route f¸hrt zun‰chst durch freies Gel‰nde und vorbei am Binsalm-Hochleger. Abschnittsweise gibt es dann Abk¸rzungsmˆglichkeiten auf einem Steig. Man gelangt zum Binsalm-Niederleger. Vom Niederleger auf einem breiten Fahrweg und einige Zeit praktisch parallel zu einem tief eingeschnittenen Tal hinunter ins Almdorf der Eng. Hinter den letzten Geb‰uden in der Eng beginnt rechter Hand der breite Fuﬂweg zur Falkenh¸tte. Der Weg steigt sanft an und f¸hrt durch Wiesen und Mischwald nach oben auf das Hohljoch (1.794 Meter). Vom Joch auf einem guten Steig unterhalb der Laliderer W‰nde hinab bis auf knapp 1.700 Meter. Dabei werden die Laliderer Reisen gequert. Der Steig zieht schlieﬂlich sanft nach oben zum Spielissjoch, die letzten Meter zur Falkenh¸tte werden auf einem Fahrweg zur¸ckgelegt.",
        "start": "Lamsenjochh¸tte",
        "ziel": "Falkenh¸tte",
        "auf": "810",
        "ab": "920",
        "hp": "1959",
        "grad": "mittelschwierig",
        "km": "12,5",
        "stunden": "4,5",
        "einkehr": "Lamsenjochh¸tte#Binsalm#Engalm#Falkenh¸tte",
        "track": "A09"
    },
    {
        "nr": "10",
        "titel": "Adlerweg-Etappe 10: Falkenh¸tte ñ Karwendelhaus",
        "text": "Diese Adlerweg-Etappe startet auf der Falkenh¸tte und f¸hrt durch Almwiesen und einem lichten Wald sanft abw‰rts zum Etappenziel, dem Karwendelhaus. Dabei quert die Route den ÑKleinen Ahornbodenì, eine Weide mit mehreren Jahrhunderte alten Ahornen.",
        "info": "Nˆrdlich unterhalb der Falkenh¸tte folgt man der Beschilderung ÑKarwendelhausì und wandert auf einem guten Steig durch Almwiesen sanft abw‰rts. Sp‰ter weiter abw‰rts ¸ber einen Fahr- bzw. Karrenweg. Vorbei an der Ladizalm mit dem historischen Almhaus und anschlieﬂend im (lichten) Wald hinunter (stets auf dem Karrenweg bleiben). Nach der ‹berquerung des meist ausgetrockneten, breiten Schotterbachbetts f¸hrt die Route zum Kleinen Ahornboden und m¸ndet in eine breite Forststraﬂe, die gleich zum Hermannvon- Barth-Denkmal und den alten Forsth‰usern unmittelbar oberhalb des Denkmals f¸hrt. Auf der Forstraﬂe links an den Forsth‰usern vorbei aufw‰rts Richtung ÑKarwendelhausì. Der Forstweg verwandelt sich im lichten Wald rasch in einen Karrenweg, sp‰ter in einen Steig. Der Steig leitet in der Folge sanft durch das liebliche Untere Filztal empor, eher er sp‰ter ins Almgel‰nde zieht (insgesamt praktisch stets in gleichbleibender Richtung). Wenig sp‰ter m¸ndet der Steig in einen Fahrweg. Nun auf dem Fahrweg weiter in gleichbleibender Richtung durch die Wiesen zum Hochalmsattel mit dem Jochkreuz. Anschlieﬂend auf dem Fahrweg ein paar Meter abw‰rts und links hin¸ber zum Karwendelhaus.",
        "start": "Falkenh¸tte",
        "ziel": "Karwendelhaus",
        "auf": "440",
        "ab": "520",
        "hp": "1843",
        "grad": "mittelschwierig",
        "km": "9",
        "stunden": "3,25",
        "einkehr": "Falkenh¸tte#Karwendelhaus",
        "track": "A10"
    },
    {
        "nr": "11",
        "titel": "Adlerweg-Etappe 11: Karwendelhaus ñ Hallerangerhaus",
        "text": "Hinauf in hˆchste Hˆhen f¸hrt die alpinistisch anspruchsvollste Adlerweg-Etappe im Karwendel. Neben dem Karwendelhaus startet die Route und f¸hrt auf die 2.749 Meter hohe Birkkarspitze. Nach dem Gipfelsieg erfolgt der Abstieg ins schˆne Hinterautal und weiter bis zum Etappenziel, dem Hallangerhaus.",
        "info": "Neben dem Karwendelhaus beginnt der markierte Steig zur Birkkarspitze. Der zieht zun‰chst recht steil und stellenweise seilversichert im felsdurchsetzten Gel‰nde durch Latschen und Lawinenverbauten empor. Es geht dann in s¸dˆstlicher Richtung und nicht mehr so steil hin¸ber ins schier endlose Schlauchkar. Die Route leitet vorbei an der Abzweigung zum Hochalmkreuz (links) und an der Abzweigung zum Brendelsteig (rechts). Man beh‰lt hier die Richtung bei und wandert etwas m¸hsam ñ teilweise in felsdurchsetztem Gel‰nde und vielfach in ‰uﬂerst unangenehmem Gerˆll ñ durch das Kar hinauf (Steinm‰nnchen). Der Steig gewinnt zunehmend an Steilheit, der letzte Abschnitt zum Schlauchkarsattel verl‰uft in s¸dwestlicher Richtung. In dem Bereich muss in der Regel ein (meist hartes) Schneefeld ¸berquert werden ñ man folgt am besten den Trittspuren. Vom Schlauchkarsattel (2.639 Meter) dann an der Birkkarh¸tte (Notunterstand) vorbei und ¸ber die seilversicherte Steiganlage in einfacher Kraxelei den Westgrat entlang hin¸ber zum Gipfel der Birkkarspitze (2.749 Meter) mit dem Kreuz. Vom Gipfel wieder zur¸ck zum Schlauchkarsattel und im S¸den hinab. Zun‰chst zieht die Route durch Blockwerk und stellenweise seilversichert steil abw‰rts ins Westliche Birkkar. Im Kar auf guten Steig weiter ñ vielfach durch Gerˆllfelder, abschnittsweise erneut recht steil. Schlieﬂlich an der orografisch linken Seite des Birkkarbachs ziemlich gerade hinunter ins Hinterautal zur Forststraﬂe. Nun im Talboden einw‰rts und Richtung ÑKastenalmì bzw ÑHallerangerhausì. Auf dem Fahrweg rechts an der Kastenalm bzw. am Jagdhaus Kasten vorbei und in der Folge im lichten Wald steil aufw‰rts (oberhalb des in dem Bereich tief eingegrabenen Lafatscherbachs). Der Fahrweg f¸hrt in eine Art Hochtal, durch das die Strecke zun‰chst sanft ansteigend bzw. beinahe eben neben dem Lafatscher Bach verl‰uft. Nach der Jagdh¸tte geht es erneut ein wenig steiler nach oben ins Almgebiet des Lafatscher-Niederlegers mit dem urigen steiler nach oben ins Almgebiet des Lafatscher-Niederlegers mit dem urigen Almhaus. Hier durch die Wiesen gem¸tlich weiter. Bei der Weggabelung rechts Richtung ÑHallerangerhausì halten (links: Hallerangeralm ñ jeweils 10 Minuten). Jetzt die letzten Hˆhenmeter empor zum Etappenziel.",
        "start": "Karwendelhaus",
        "ziel": "Hallerangerhaus",
        "auf": "1440",
        "ab": "1450",
        "hp": "2749",
        "grad": "schwierig",
        "km": "14",
        "stunden": "8",
        "einkehr": "Karwendelhaus#Kastenalm#Hallerangerhaus#Hallerangeralm",
        "track": "A11"
    },
    {
        "nr": "12",
        "titel": "Adlerweg-Etappe 12: Hallerangerhaus ñ  Nordkette Innsbruck",
        "text": "Diese Etappe f¸hrt vom Hallangerhaus zum Hafelekar auf der Innsbrucker Nordkette. Der Weg dorthin f¸hrt am ÑZugspitzblickì vorbei, wo man bei schˆnem Wetter einen Blick auf Deutschlands hˆchsten Berg erhaschen kann. Am Hafelekar wartet dann noch der einzigartige Blick auf die Landeshauptstadt.",
        "info": "Vor der H¸tte zun‰chst auf dem Steig Richtung ÑLafatscher Jochì. Der Steig f¸hrt in ein Schuttkar, das zunehmend steiler und schm‰ler wird. Die Route leitet dann bald durch den so genannten ÑDurchschlagì (hier wurde der alte Saumweg durch den Felsen gebrochen) und wenig sp‰ter ñ vorbei an einem Kreuz ñ sanft hinauf auf einen Boden (in dem Bereich Abzweigemˆglichkeit zur Speckkarspitze). ‹ber den Boden geht es in nˆrdlicher Richtung gem¸tlich zum Lafatscher Joch. Am Joch der Beschilderung ÑPfeish¸tteì folgen. Auf dem Steig sanft hinunter und sich an ÑPfeish¸tteì orientieren bzw. in Folge an ÑPfeish¸tte ¸ber Wilde-Bande-Steigì. Auf dem urt¸mlichen ÑWilde-Bande-Steigì vielfach durch Latschen, mehrmals Rinnen ¸berquerend, leicht ansteigend hin¸ber bis zum Einstieg ins Kar unterhalb des Stempeljochs. Hier an ÑStempeljochì bzw. ÑPfeish¸tteì orientieren. Die Steiganlage (mit Brettern gebaut, zahlreiche Drahtseile) durch das Kar wird zunehmend steiler, der (zun‰chst schottrige) Untergrund daf¸r weiter oben fester. Vom Joch rechter Hand hinunter und durch Wiesen bzw. Almgebiet gem‰chlich zur Pfeish¸tte. Direkt bei der Pfeish¸tte beginnt der beschilderte ÑGoethewegì (Nr. 219). Der f¸hrt als Fuﬂweg bzw. sp‰ter als Steig gem¸tlich ansteigend in den Kessel s¸dlich des Schutzhauses. Bei einer Weggabelung Richtung ÑMandlscharteì bzw. ÑHafelekar Bergstationì, bei der folgenden Weggabelung rechter Hand weiter (links ginge es zur Arzler Scharte) und in einer weiten Schleife durch ein Schuttkar empor zur Mandlscharte. Von der Scharte jenseits durch Gerˆll hinab. Der jetzt wieder gute und recht breite Steig quert nun praktisch stets auf derselben Hˆhe unter den Felsen die Schuttreisen (toller Blick zur R¸ckseite der Nordkette). Nach einem kurzen Anstieg wird auf die Inntalseite gewechselt und dort in Serpentinen ein paar Meter abgestiegen. Anschlieﬂend auf dem bequemen Steig im oberen Bereich der absch¸ssigen, teilweise grasbewachsenen S¸dflanke der Nordkette insgesamt leicht ansteigend nach Westen zur Hafelekar - Bergstation (stets der Beschilderung ÑHafelekar Bergstationì bzw. ÑGoethewegì folgen). Zum Schluss abwechselnd links bzw. rechts vom Grat. Der Goetheweg ist vielfach ausgezeichnet versichert. Bei der Talfahrt mit der renovierten Nordkettenbahn und der neuen Hungerburgbahn gelangt man direkt in das Stadtzentrum zum Congress Innsbruck, wobei der Abstieg auch zu Fuﬂ mˆglich ist, wo als Zwischenstation eine Besichtigung des Alpenzoos eingebaut werden kann.",
        "start": "Hallangerhaus",
        "ziel": "Innsbruck",
        "auf": "1150",
        "ab": "970",
        "hp": "2280",
        "grad": "schwierig",
        "km": "13",
        "stunden": "5,5",
        "einkehr": "Hallerangerhaus#Hallerangeralm#Pfeish¸tte#Bergstation Hafelekar",
        "track": "A12"
    },
    {
        "nr": "13",
        "titel": "Adlerweg-Etappe 13: Innsbruck ñ Zirbenweg ñ Innsbruck",
        "text": "Diese Adlerweg-Etappe verl‰uft am Zirbenweg entlang durch einen der ‰ltesten Zirbenbest‰nde Europas. Von verschiedenen Aussichtspunkten gibt es immer wieder traumhafte Ausblicke auf Innsbruck und Hall sowie Teile des Inntals oder das Landschaftsschutzgebiet Viggartal.",
        "info": "Von Innsbruck/Hauptbahnhof mit dem Bus bzw. der Straﬂenbahn nach Igls/Talstation Patscherkofelbahn und mit der Seilbahn zur Bergstation Patscherkofel. Bei der Bergstation (1.964 Meter) gleich der Beschilderung †ÑZirbenwegì (Nr. 350) folgen, der direkt oberhalb des ÑSchutzhauses Patscherkofelì auf breitem Pfad Richtung Osten f¸hrt. Hier beginnt gleichzeitig der ÑNaturlehrpfad Patscherkofelì des Alpenvereins. Der breite Pfad bzw. Steig zieht knapp oberhalb der Waldgrenze im freien, aber nicht vˆllig baumlosen Gel‰nde (Zirben) insgesamt leicht ansteigend hin¸ber zur etwas versteckten Boscheben H¸tte (2.035 Meter, hier Abzweigemˆglichkeit ins Viggartal zum Meiﬂner Haus; bis hierher f¸hrt der Naturlehrpfad entlang des Zirbenwegs). Von Boscheben in gleich bleibender Richtung weiter und nˆrdlich unterhalb der kleinen Gipfel bleiben (nirgendwo ins Tal absteigen). Auf dem Steig hin¸ber zur Tulfeinalm und von dort in wenigen Minuten ein paar Meter empor zum Halsmarterlift. Der Zirbenweg verl‰uft nach Boscheben leicht an- und absteigend jedoch ohne wesentliche Hˆhen‰nderung entlang bzw. knapp ¸ber der 2.000-Meter-Marke ñ in der Regel etwas oberhalb der Waldgrenze, jedoch nicht im baumfreien Gebiet (Zirben!). Mit dem Lift nach Tulfes, von dort mit dem Bus nach Igls und von Igls mit dem Bus bzw. der (Straﬂen)bahn zur¸ck nach Innsbruck. Wer wieder zu Fuﬂ zur Talstation der Patscherkofelbahn gehen mˆchte, der geht von der Talstation Glungezerbahn am Speckbacherweg ¸ber Rinn und Sistrans nach Igls (Gehzeit ca. 3 Std.). Von der Talstation Patscherkofel/Igls zum Hauptbahnhof geht es von Igls nach Vill durch den Wald zur Poltenh¸tt; Haltestelle Tantegert, Abzweigung Richtung Bretterkeller, ¸ber Br¸cke Autobahn ¸berqueren, ca. 200 Meter Richtung Westen zum Gasthof Bierstindl ñ Stift Wilten ñ Leopoldstraﬂe ñ rechts zur Fuﬂg‰ngerunterf¸hrung Olympiabr¸cke ñ S¸dbahnstraﬂe bis zum Bahnhof (Gehzeit ca. 1 Ω Std.).",
        "start": "Innsbruck Hauptbahnhof",
        "ziel": "Innsbruck Hauptbahnhof",
        "auf": "300",
        "ab": "200",
        "hp": "2060",
        "grad": "leicht",
        "km": "8",
        "stunden": "2,5",
        "einkehr": "Patscherkofelhaus#Boschebenalm#Tulfeinalm",
        "track": "A13"
    },
    {
        "nr": "14",
        "titel": "Adlerweg-Etappe 14: Innsbruck ñ Solsteinhaus",
        "text": "Mit der Mittenwald- oder Karwendelbahn geht es von Innsbruck nach Hochzirl und weiter nach Seefeld. Von dort f¸hrt diese Etappe zum Solsteinhaus im Karwendel.",
        "info": "Mit der Mittenwaldbahn von Innsbruck oder zu Fuﬂ vom Bahnhof in Richtung Westen der Salurnerstraﬂe bis zur Triumphpforte folgend ñ dann nach links in die Maria- Theresien-Straﬂe bis diese immer geradeaus in die Altstadt zum Goldenen Dachl f¸hrt ñ dort rechts vorbei in die Domgasse bis zum Dom zu St. Jakob. Dem Jakobsweg durch Innsbruck weiter nach Kranebitten, Vˆls, Kematen folgend und dann ab Kematen dem Wanderweg ¸ber die Innbr¸cke in Richtung Zirl nehmen, um dann weiter durch die Ehnbachklamm in Richtung Plainer zum Bahnhof Hochzirl und direkt vom Bahnhof der Beschilderung ÑSolsteinhausì folgen. Nˆrdlich der Gleise gleich auf einem guten Steig in den dichten Wald hinein. Der Steig m¸ndet nach kurzer Zeit in einen Karrenweg, auf diesem direkt und recht steil nach oben. Bald m¸ndet links der Weg vom Krankenhaus Hochzirl ein, weiter aufw‰rts und in nordˆstlicher Richtung steil durch den Wald. Nach der ‹berquerung des kleinen Bachs, der vom Brunnenschrofen herunterrinnt, ein kurzes St¸ck fast eben bzw. nur sanft ansteigend dahin. Die Route ‰hnelt jetzt beinahe einem Fahrweg und zieht bald wieder kr‰ftiger empor. In einer Hˆhe von rund 1.350 Metern trifft die Route mit einem breiten Forstweg zusammen ñ hier weiter nach oben. Es geht oberhalb einer kleinen Schlucht vorbei und nach dem Bach ¸ber einen Steig im lichter werdenden Wald bzw. durch die Latschen empor ins freie Almgebiet bei der lieblichen Solnalm. Von der Solnalm erblickt man erstmals das Solsteinhaus. Rechts an der Alm vorbei und in nˆrdlicher Richtung taleinw‰rts auf das Hˆllkar zu. Dabei wird die eine oder andere Schuttrinne ¸berquert. Der Steig ¸berquert dann die Ausl‰ufer des Hˆllkars sowie den Bach und zieht schlieﬂlich in den Latschen gem¸tlich den Hang nach oben zum Erlsattel mit dem Solsteinhaus.",
        "start": "Innsbruck Hauptbahnhof",
        "ziel": "Solsteinhaus",
        "auf": "940",
        "ab": "70",
        "hp": "1805",
        "grad": "mittelschwierig",
        "km": "7",
        "stunden": "2,75",
        "einkehr": "Solsteinhaus",
        "track": "A14"
    },
    {
        "nr": "15",
        "titel": "Adlerweg-Etappe 15: Solsteinhaus ñ Leutasch",
        "text": "Mitten durchs Karwendel f¸hrt diese Etappe und verl‰uft ¸ber die Eppzirler Scharte in das Leutaschtal und weiter zu den 24 Weilern der Gemeinde Leutasch. Dabei werden Almgebiete, Mischw‰lder und die Gieﬂenbachklamm durchquert.",
        "info": "Beim Solsteinhaus der Beschilderung ÑEppzirler Scharteì bzw. ÑEppzirler Almì folgen. Zun‰chst auf markiertem Steig durch das Almgebiet der Erlalm hinauf. Der Steig leitet in der Folge durch Schutt und Felsen hin¸ber zum Beginn des Schuttkars, empor zur Eppzirler Scharte. Beim Anstieg durch das Kar teilt sich der Steig ñ hier rechter Hand Richtung ÑEppzirler Scharteì (Nr. 212) und steil, aber auf gutem Steig zu der Scharte zwischen Kuhlochspitze und Erlspitze. Jenseits durch das oben steile und sp‰ter sehr weite Schuttkar (Kuhloch) ebenfalls auf gutem Steig und teilweise in Serpentinen hinab. Bei etwa 1700 Meter taucht der Steig ein in gr¸nes Almgebiet. Es folgt noch einmal eine kurze Steilstufe (Schutt), ehe die Route endg¸ltig den Almboden erreicht. In der Folge sanft absteigend und schlieslich parallel zum (ausgetrockneten) Bachbett hinaus zur Eppzirler Alm. Von der Alm auf dem breiten Fahrweg im Weidegebiet gemutlich abw‰rts und stets durch das Eppzirler Tal in gleichbleibender Richtung auswarts. Vorbei an der Abzweigung zur Oberbrunnalm (Abzweigung bei 1.200 Meter) und weiter meist sanft absteigend Talauswarts. Der Fahrweg fuhrt jetzt den Giesenbach entlang (abwechselnd links und rechts vom Bach) und in die ñ zun‰chst noch bewaldete ñ Giesenbachklamm. Die Klamm wird zunehmend felsiger. Der Weg leitet schlieﬂlich zum Parkplatz f¸r die Eppzirler Alm im Scharnitzer Ortsteil Giesenbach. Dann das Gleis und die Hauptstraﬂe ¸berqueren, in der Siedlung die erste Straﬂe rechts Richtung ÑScharnitzì nehmen, anschlieﬂend links Richtung ÑHoher Sattelì. Spater Richtung ÑBogenschiesstandì bzw. ÑScharnitzì, dann links ab Richtung ÑLeutaschì und bald rechter Hand den Forstweg ÑLeutasch ¸ber Hohen Sattelì nehmen. Nach dieser kurzen ebenen Passage in Giesenbach f¸hrt der Forstweg m‰ﬂig steil hinauf und in der Folge sanft im lichten Mischwald durch die Sattelklamm empor. Ab dem Wegende zieht ein Steig im lichten Wald den Hang entlang und (im Mittelteil) recht zugig aufw‰rts. Der Steig mundet in einen Weg ñ hier in gleichbleibender Richtung weiter zum Hohen Sattel, stets der Beschilderung ÑLeutasch/Ahrnì folgend. Jenseits des Sattels auf breitem Forstweg im lichten Wald (mitunter recht steil) durch das Satteltal hinunter nach Leutasch/Ahrn zur Br¸cke ¸ber die Leutascher Ache (unmittelbar vor dem Ziel nichts links abzweigen).",
        "start": "Solsteinhaus",
        "ziel": "Leutasch/Ahrn",
        "auf": "870",
        "ab": "1530",
        "hp": "2110",
        "grad": "mittelschwierig",
        "km": "20",
        "stunden": "6,5",
        "einkehr": "Solsteinhaus#Eppzirleralm",
        "track": "A15"
    },
    {
        "nr": "16",
        "titel": "Adlerweg-Etappe 16: Leutasch ñ Ehrwald",
        "text": "Vorbei an den lieblichen Almen des Gaistals und entlang des nat¸rlichen Bachbetts der Leutascher Ache f¸hrt diese Adlerweg-Etappe in Richtung Zugspitze.",
        "info": "Im Leutascher Ortsteil Ahrn bei der Br¸cke ¸ber die Leutascher Ache (Ausgangspunkt f¸r den Hohen Sattel) an der orografisch linken Seite der Ache auf dem Fuﬂweg Richtung ÑWeidachì. Bald wird auf die rechte Seite gewechselt (in diesem Bereich Richtung ÑUnterweidachì bzw. ÑAchweg Weidachì). Man folgt dann im Prinzip auf dem Achweg stets der Leutascher Ache an deren orografisch rechtem Ufer bis zum Kalvarienberg am Beginn des Gaistals. Hier auf einem Eisensteg die Ache ¸berqueren, ein paar Meter taleinw‰rts gehen, beim Mauth‰uschen gleich wieder zur¸ck auf die rechte Bachseite wechseln und dort taleinw‰rts weiter. Kurz vor dem Salzbachparkplatz der Beschilderung ÑAlmenparadies Gaistalì folgen und abermals die Ache ¸berqueren. Dann jedoch nicht hinaus zum Parkplatz, sondern vorher links dem breiten Fahrweg ins Gaistal folgen. Nach wenigen Metern rechts abzweigen zum ÑGanghoferwegì. Dieser breite Fuﬂweg f¸hrt zun‰chst ein kurzes St¸ck steil nach oben. Wenig sp‰ter sanft ansteigend im lichten Wald und entlang von Wiesen unterhalb der H‰mmermoosalm vorbei stets taleinw‰rts (ÑGaistalalmì, ÑTillfuﬂalmì). Der Weg ¸berquert den Leitenbach und f¸hrt nun ein paar Meter hinunter zur Gaistalalm (Ende des Ganghoferwegs). Von der Einkehr geht es in gleich bleibender Richtung zun‰chst ¸ber Almwiesen weiter zur Tillfuﬂalm. Der Fuﬂweg verwandelt sich bald in einen Steig, taucht in den Wald ein und steigt geringf¸gig an. Schlieﬂlich kaum sp¸rbar hinab zur Tillfuﬂalm. Von da weiter auf dem breiten Talweg nach Westen, parallel zum Bachbett der Leutascher Ache bzw. des Gaistalbachs. Bei der Weggabelung geradeaus (ÑEhrwalder Alm ¸ber Igelseeì). Die Route verl‰uft zwischen den immer markanter werdenden Mieminger Bergen links und dem Wettersteingebirge rechts. Es geht insgesamt sanft aufw‰rts und ¸ber eine Kuppe zum Igelsee. Hinter dem See bei der Weggabelung rechts und etwas steiler empor bis rund 1.600 Meter (hier Einm¸ndung des Steigs von der Pestkapelle). Weiter auf der Forststraﬂe hinunter zur Ehrwalder Alm und zur Bergstation der Ehrwalder Almbahn. Unterhalb der Ehrwalder Alm beginnt der ÑWiesenweg nach Ehrwaldì. Zun‰chst durchs Skigebiet, an der Weggabelung geradeaus bzw. rechts und ein St¸ck steil durch den Wald. Sp‰ter leitet der Fuﬂweg durch herrliche Bergm‰hder hinaus zur Talstation der Ehrwalder Almbahn. Entweder auf dem Zufahrtsweg oder auf dem Altm¸hlensteig (beginnt ein paar Meter s¸dwestlich der Talstation auf der orografisch linken Seite des Geiﬂbachs) hinaus nach Ehrwald.",
        "start": "Leutasch/Ahrn",
        "ziel": "Ehrwald",
        "auf": "590",
        "ab": "730",
        "hp": "1597",
        "grad": "leicht",
        "km": "23",
        "stunden": "7",
        "einkehr": "Gaistalalm#Tillfussalm#Erwalder Alm",
        "track": "A16"
    },
    {
        "nr": "17",
        "titel": "Adlerweg-Etappe 17: Ehrwald ñ Lorea H¸tte",
        "text": "Moosweg, Blindsee, Via Claudia Augusta oder Schloss Fernstein: Von einem Landschaftsjuwel zum n‰chsten geht es entlang dieser Adlerweg-Etappe.",
        "info": "In Ehrwald beginnt zwischen dem Hotel ÑGr¸ner Baumì und dem Sparmarkt der beschilderte ÑMoosweg nach Lermoosì. Nach der ÑGroﬂen Moosbr¸ckeì ¸ber die Loisach dann entweder links oder rechts vom Lussbach bis zum Ortsanfang von Lermoos. Dort durch den Ort zur Talstation der Grubigsteinbahn (bis hierher kein nennenswerter Hˆhenunterschied). Mit dem Lift zur Grubigalm (1.720 Meter). Hinter der Talstation der neuen 6-er-Sesselbahn den Fuﬂweg Nr. 15 nehmen (N‰he Wegkreuz) und ñ ein wenig auf und ab ñ im Wald nach oben bis auf rund 1.750 Meter. Jetzt auf dem breiten Fuﬂweg im Wald gem¸tlich hinunter. Die Route taucht nun in die Latschen ein (Blick zum Blindsee, stellenweise etwas steiler hinab). Die Strecke f¸hrt weiter unten erneut in den Wald. Der Fuﬂweg bzw. Steig m¸ndet in einen Forstweg ñ an der Stelle weiter hinunter. Die Route f¸hrt zur Fernpassbunde straﬂe. Neben der Straﬂe etwa 5 Minuten rechts hin¸ber zum Fernpass. Nˆrdlich vom Gasthof Fernpass auf der alten Rˆmerstraﬂe sanft hinunter (ÑNassereithì, ÑVia Claudia Augustaì). Bei der Weggabelung rechts weiter, anschlieﬂend bald links hinunter Richtung ÑFernsteinì, ÑNassereithì (kurz eine Art Schotterpiste). Bald am Schanzlsee vorbei (nach dem See auf der Route f¸r Radfahrer und Fuﬂg‰nger bleiben). Die alte Rˆmerstraﬂe (kurzer Abschnitt ein Steig) leitet gem¸tlich hinab zum Schloss Fernstein mit dem Hotel. Vom Schloss Fernstein auf der alten Rˆmerstraﬂe leicht bergab weiter. Nach wenigen Metern zweigt rechts der Steig zur Loreah¸tte in den Wald ab. Auf dem Steig sehr steil und vielfach in Serpentinen neben dem Bach durch den Wald empor. Der Steig f¸hrt sp‰ter durch Latschenbest‰nde und zum Schluss ¸ber weite Almbˆden ñ jetzt weniger steil ñ zur Loreah¸tte.",
        "start": "Ehrwald",
        "ziel": "Lorea H¸tte",
        "auf": "1170",
        "ab": "1190",
        "hp": "2022",
        "grad": "mittelschwierig",
        "km": "19",
        "stunden": "5,75",
        "einkehr": "Grubigalm #Hotel Schloss Fernstein#Lorea H¸tte",
        "track": "A17"
    },
    {
        "nr": "18",
        "titel": "Adlerweg-Etappe 18: Lorea H¸tte ñ Anhalter H¸tte",
        "text": "Diese Route f¸hrt in eines der entlegensten Gebiete Tirols und ¸berrascht stets aufs Neue. Almen, Steilw‰nde und wilde Bergflanken, Almrosen und Bergblumen sind stille Begleiter, die gesunde, klare Luft der Antrieb f¸r diese Adlerweg-Etappe.",
        "info": "Bei der Lorea H¸tte h‰lt man sich an die Beschilderung ÑLoreakopfì und wandert auf dem Steig ¸ber Almbˆden sanft hinauf. An der folgenden Steiggabelung links (ÑLoreakopfì), vielfach durch Schutt und oben steil empor zur Loreascharte. Auf der anderen Seite auf dem Steig durch eine Grasflanke rasant hinunter ins Heimbachtal. Im Talboden linker Hand Richtung ÑNassereithì halten. Jetzt f¸hrt ein schmaler Steig neben dem Bach (in einer Passage direkt im Bachbett) leicht absteigend talausw‰rts. An der Stelle, wo das Tal einen deutlich sichtbaren Rechtsbogen einlegt, wird auf die orografisch rechte Bachseite gewechselt (Markierung am Felsen rechts nicht ¸bersehen!). Fortan leitet das Steiglein in den Wald und in s¸dwestlicher Richtung hinunter ins Tegestal zur Forststraﬂe (Einm¸ndung bei rund 1.400 Meter). Nun gem¸tlich ansteigend taleinw‰rts weiter, vorbei an der Abzweigung zur Heiterwandh¸tte (links) ñ immer in dem hier sanften Tegestal bleiben. Hinein ins Almgebiet und gem¸tlich nach oben zum Schweinsteinjoch (1.564 Meter, hier zweigt Route nach Sinnesbrunn ab). Vom Joch in gleichbleibender Richtung sanft durch das Almgebiet hinunter zur Hinteren Tarrentonalm (1.519 Meter). Bei der Alm der Beschilderung ÑAnhalter H¸tteì folgen und auf einem breiten Forstweg gem¸tlich bergw‰rts. An der Weggabelung wenig sp‰ter links halten und dem Bach entlang wandern. Die Route leitet vorbei an der Schaferh¸tte und verwandelt sich in einen Steig. Nun im freien Gel‰nde unterhalb der Heiterwand dem Steig bzw. den Steigspuren folgen, meist gem‰chlich ansteigend zum Hinterbergjoch (2.202 Meter). Vom Hinterbergjoch ¸ber einen steilen Grashang hinunter (ÑSchwarze Erdeì) und das Kar querend fast eben hin¸ber zum Kromsattel (Steigspuren). Vom Kromsattel leicht absteigend durch Wiesen und Almgebiet zur Anhalter H¸tte.",
        "start": "Lorea H¸tte",
        "ziel": "Anhalter H¸tte",
        "auf": "1200",
        "ab": "1180",
        "hp": "2315",
        "grad": "mittelschwierig",
        "km": "16",
        "stunden": "6,5",
        "einkehr": "Hotel Schloss Fernstein#Lorea H¸tte#Hintere Tarrentonalm#Anhalter H¸tte",
        "track": "A18"
    },
    {
        "nr": "19",
        "titel": "Adlerweg-Etappe 19: Anhalter H¸tte ñ Hanauer H¸tte",
        "text": "Eine intakte Berglandschaft, Wasserf‰lle und pl‰tschernde B‰che sind die Begleiter auf dieser Adlerweg-Etappe. Interessante Einblicke und Ausblicke bieten sich vom Angerletal, der Weiler Pfafflar ¸berrascht mit seinen Ñgestreiftì wirkenden Holzh‰usern.",
        "info": "Von der Anhalter H¸tte zun‰chst ein paar Meter in westlicher Richtung hinunter und dann auf dem Steig gem‰chlich ansteigend empor zum Steinjˆchl (Seilsicherungen). Jenseits der Einsattelung vorerst direkt hinab, dann jedoch gleich sanft absteigend durch Wiesen und Latschen die H‰nge querend in s¸dwestlicher Richtung zum Hahntennjoch mit seiner alpinen Szenerie. An der Stelle, wo die Route zur Straﬂe hinauf leitet, ¸ber Almwiesen den roten Markierungspfeilen folgend, rechter Hand auf einem Steig nach Westen hinunter ñ wenig sp‰ter folgt Beschilderung ÑHanauer H¸tteì. Die Strecke verl‰uft nˆrdlich der Straﬂe entlang eines Steigs bzw. weiter unten auf einem Karrenweg durch Almwiesen, Latschen und lichten Mischwald gem¸tlich hinab. Sie f¸hrt in dem Bereich auch ein kurzes St¸ck durch eine kleine Schlucht. Die Route kommt in Folge zu einer Linkskehre der Straﬂe. Ab hier wandert man auf dem Gr¸nstreifen nˆrdlich der Straﬂe abw‰rts (Weg Nr. 601 an der Wand angeschrieben). Man gelangt bald zu den H‰usern von Pfafflar (hier best¸nde Abzweigemˆglichkeit ins Fundaistal zum Galtseitejoch f¸r den alternativen Zustieg zur Hanauer H¸tte). F¸r den Normalweg jedoch an der Straﬂe durch Pfafflar hindurch und beim Schild ÑNach Bodenì linker Hand ¸ber die Straﬂe und den Bach. In Folge auf einem idyllischen Steig entlang des Bachs hinunter (bei H‰usergruppe erneut Abzweigemˆglichkeit zum Galtseitejoch f¸r den alternativen Zustieg). F¸r den Normalweg aber wechselweise auf dem Steig bzw. Karrenweg in westlicher Richtung ñ mitunter recht steil ñ abw‰rts in die Ortschaft Boden zum Parkplatz f¸r die Hanauer H¸tte. Hier gleich den Fundaisbach ¸berqueren und der Beschilderung ÑHanauer H¸tteì folgen. Die Route verl‰uft jetzt auf einem guten Forstweg und zieht nach der ‹berquerung des Angerlebachs in das Angerletal. Ab der Br¸cke steigt die Strecke wieder gem¸tlich an und f¸hrt jetzt durch lichten Wald. Bald zeigt sich bereits die Hanauer H¸tte auf dem Plateau ¸ber dem Tal. Es folgt eine kurze absteigende Passage, ehe der Weg erneut ñ neben dem breiten Schotterbachbett im freien Gel‰nde ñ hinauf durch das Angerletal leitet. Ab der Talstation der Materialseilbahn verwandelt sich der Fahrweg in einen Steig, der zuletzt recht steil in Serpentinen (hier auf dem Sommerweg bleiben) zur H¸tte empor zieht.",
        "start": "Anhalter H¸tte",
        "ziel": "Hanauer H¸tte",
        "auf": "750",
        "ab": "870",
        "hp": "2188",
        "grad": "mittelschwierig",
        "km": "12,5",
        "stunden": "3,75",
        "einkehr": "Anhalter H¸tte#Haunauer H¸tte",
        "track": "A19"
    },
    {
        "nr": "20",
        "titel": "Adlerweg-Etappe 20: Hanauer H¸tte ñ W¸rttemberger Haus",
        "text": "Auf dieser Etappe von der Hanauer H¸tte zum W¸rttemberger Haus wartet neben einem herrlichen Tiefblick auf den Steinsee ein herrlicher Panoramablick auf die umliegenden Gipfel. Almen, Bergblumen, Kare, Schuttreisen und Felsw‰nde machen die Tour zu einem abwechslungsreichen Erlebnis.",
        "info": "Direkt hinter der Hanauer H¸tte folgt man dem Schild ÑW¸rttemberger Hausì. Wenig sp‰ter teilt sich der Steig ñ wir gehen an der Stelle Richtung ÑSteinseeh¸tteì (nicht ÑW¸rttemberger Hausì). Knapp vor dem Bach teilt sich der Steig noch einmal ñ hier ist zweimal ÑSteinseeh¸tteì angeschrieben. F¸r die Hintere/ ÷stliche Dremelscharte w‰hlt man die Route Nr. 625 (links). Ab nun folgt man stets der Beschilderung ÑSteinseeh¸tteì. Es geht bald ¸ber einen steilen Hang hinauf und in den Kessel zwischen Dremelspitze und Kleiner Schlenkerspitze. Nach der Querung von Schuttreisen zieht ein tadelloser Steig durch ein Schuttkar steil empor in Richtung ÷stliche Dremelscharte. Im obersten Teil muss eine schmale, seilversicherte Rinne (Schutt) durchquert werden. Auf der anderen Seite leitet der Steig durch Wiesen zun‰chst steil hinunter und anschlieﬂend meist sanft absteigend am Steinsee vorbei zur Steinseeh¸tte. Ab der H¸tte abermals ein kurzes St¸ck abw‰rts, dann gem¸tlich ansteigend zur Steinkarscharte. Dahinter werden Grash‰nge bzw. Schuttreisen gequert, ehe der Steig st‰rker ansteigend durch Felsen und anschlieﬂend durch Schotter zur Roﬂkarscharte f¸hrt. Nach der Scharte in einer engen Felsrinne (Seile) steil hinunter, sp‰ter in dem etwas breiter werdenden Kar auf Schutt hinab in ein Becken. Anschlieﬂend quert der Steig Wiesenh‰nge und Schuttreisen und steigt dabei m‰ﬂig an. Schlieﬂlich zieht die Route steil empor zum Geb‰udjoch. Jenseits auf schwarzer Erde auf einem schlechten, nicht versicherten Steig steil abw‰rts und hin¸ber zu Grash‰ngen, die gequert werden. Schlieﬂlich in Serpentinen hinunter zum W¸rttemberger Haus.",
        "start": "Haunauer H¸tte",
        "ziel": "W¸rttemberger Haus",
        "auf": "1240",
        "ab": "930",
        "hp": "2480",
        "grad": "schwierig",
        "km": "11",
        "stunden": "7",
        "einkehr": "Hanauer H¸tte#Steinsee H¸tte#W¸rttemberger Haus",
        "track": "A20"
    },
    {
        "nr": "21",
        "titel": "Adlerweg-Etappe 21: W¸rttemberger Haus ñ Memminger H¸tte",
        "text": "Steinbˆcke gelten, so wie das Edelweiﬂ, als ein Symbol der Alpen. Entlang dieser Adlerweg-Etappe zur Memminger H¸tte ergeben sich immer wieder Mˆglichkeiten, Steinbˆcke in freier Natur zu beobachten.",
        "info": "Von der H¸tte auf einem Steig zun‰chstein kurzes St¸ck hinunter. Dann werden sanft ansteigend Wiesenh‰nge und einSchuttkar gequert, ehe der Steig mitunter steil durch eine felsdurchsetzte Grasflanke (eine seilversicherte Stelle) zum Grat leitet. Nun links und rechts des Grats fast eben nach Norden zum Gipfel der Groﬂbergspitze (Holzkreuz). Von der Groﬂbergspitze f¸hrt die Route am Gratr¸cken ein kleines St¸ck sanft hinab. Ein Felsriegel wird ñ ansteigend ñ mit Hilfe von Drahtseilen ¸berwunden, anschlieﬂend mit wenigen Schritten nach oben zum Groﬂbergkopf. Jetzt geht es links vom Grat auf dem schottrigen Steig recht absch¸ssig und ausgesetzt wieder hinunter und vorbei am Groﬂbergjoch. Danach werden ñ zun‰chst weiter absteigend ñ Wiesenh‰nge gequert, bis der Steig erneut hinaufzieht. Er quert ein Schuttkar und f¸hrt zum Schluss steiler empor zur Seescharte. Von dort auf der anderen Seite durch Schutt, Gerˆll und auf erdigem Boden hinab. Der Steig leitet oberhalb einer kleinen Schlucht entlang und f¸hrt ins Wiesengel‰nde. Schlieﬂlich vorbei am grˆﬂten See im Bereich der H¸tte ans Etappenziel.",
        "start": "W¸rttemberger Haus",
        "ziel": "Memminger H¸tte",
        "auf": "670",
        "ab": "650",
        "hp": "2623",
        "grad": "schwierig",
        "km": "7",
        "stunden": "5",
        "einkehr": "W¸rttemberger Haus#Memminger H¸tte",
        "track": "A21"
    },
    {
        "nr": "22",
        "titel": "Adlerweg-Etappe 22: Memminger H¸tte ñ Ansbacher H¸tte",
        "text": "Diese Etappe am Adlerweg f¸hrt durch den unber¸hrtesten Teil der Lechtaler Alpen. Sie h‰lt neben Stille und Einsamkeit auch herrliche Aussichtspunkte und Naturerlebnisse bereit: weidende Schafe, Zirben- und L‰rchenw‰lder und saftig gr¸ne Almen erfreuen das Auge, gem¸tliche H¸tten sorgen f¸r z¸nftige Verpflegung.",
        "info": "Von der Memminger H¸tte auf einem schmalen, lehmigen und bei N‰sse rutschigen Steig zun‰chst direkt und bald recht j‰h ¸ber Wiesenh‰nge hinab in Richtung Parseiertal. In der Folge quert der Steig (Wiesen)h‰nge (mehrmals durch Tobel) und zieht dann wieder s¸dwestlich hinunter ins Parseiertal (Drahtseile im unteren Bereich). Dieser erste Abschnitt verl‰uft meist in absch¸ssigem Gel‰nde. Auf der anderen Seite auf tadellosem Steig vorerst m‰ﬂig steil durch lichten Wald, sp‰ter sch‰rfer durch Wiesengel‰nde empor. Man gelangt in der Folge ins Langkar, an dessen rechter Seite (im Sp‰tsommer neben dem Schneefeld) der sehr gute Steig (kaum Gerˆll) m‰ﬂig ansteigend verl‰uft. Sp‰ter wird die Route steiler und zieht nach links hin¸ber. Schlieﬂlich durch eine Art Kamin (seilversichert) recht steil und teilweise auf schwarzer Erde (Achtung bei N‰sse!) nach oben zur Grieﬂlscharte. Anschlieﬂend mit leichtem Hˆhenverlust und kurzem Gegenanstiegrecht steil und teilweise auf hin¸ber zum Winterjoch (kurz unterhalb des Winterjochs zweigt der Augsburger Hˆhenweg ab). Vom Winterjoch ein kleines St¸ck, ¸ber Schutt abw‰rts, hinter dem Stierkopf vorbei und jetzt felsiger empor zur Kopfscharte. Von der Kopfscharte quert der Steig die Grash‰nge und zieht schlieﬂlich ñ etwas an- und absteigend ñ nach S¸den zur Ansbacher H¸tte.",
        "start": "Memminger H¸tte",
        "ziel": "Ansbacher H¸tte",
        "auf": "1040",
        "ab": "900",
        "hp": "2625",
        "grad": "schwierig",
        "km": "10",
        "stunden": "6",
        "einkehr": "Memminger H¸tte#Ansbacher H¸tte",
        "track": "A22"
    },
    {
        "nr": "23",
        "titel": "Adlerweg-Etappe 23: Ansbacher H¸tte ñ Kaiserjochhaus",
        "text": "Diese anspruchsvolle Adlerweg-Etappe, die mit einem herrlichen Panoramablick auf die ÷tztaler Alpen belohnt, f¸hrt hoch ¸ber dem Stanzertal durch Schuttreisen, Kare und Schrofen. Etappenziel ist die Ansbacher H¸tte.",
        "info": "Von der Ansbacher H¸tte sanft ansteigend auf einem guten Steig hinauf zum Flarschjoch(kurz unterhalb des Jochs Abzweigemˆglichkeit zur Memminger H¸tte). Vom Flarschjoch f¸hrt der Steig durch Schutt und Wiesen sanft hinunter Richtung Knappenbˆden und dann durch Schuttreisen fast eben hin¸ber zum Alperschonjoch mit dem kleinen Kreuz. Nun f‰llt der Steig zun‰chst ein wenig ab, ehe er (in Serpentinen) wieder nach oben f¸hrt und schlieﬂlich zum Vordersee hinunter leitet. Diese Passage durch die S¸dabbr¸che der Vorderseespitze heiﬂt Haas-Weg. Der Haas-Weg quert meist Wiesen, sowie absch¸ssige, schrofige Felsflanken und Rinnen (vielfach versichert). Ab dem Vordersee geht es vorerst m‰ﬂig steil in Richtung Hinterseejoch. Zum Joch hin nimmt der Steig deutlich an Steilheit zu und zieht in Serpentinen auf erdigem Grund zu der Einsattelung. Jenseits des Hinterseejochs geht es ñ abermals in Serpentinen ñ m‰ﬂig steil hinab. Der Steig quert dann leicht abfallend die Schuttreisen hin¸ber Richtung Westen und steigt ein St¸ck unter der Kridlonscharte erneut an (in diesem Bereich erdiger, mitunter rutschiger Untergrund). Schlieﬂlich etwas ausgesetzt im Fels mit Hilfe von Drahtseilen durch einen Kamin empor zur Kridlonscharte. Auf der anderen Seite durch Bergwiesen hinunter und an einer Felsnase vorbei. Der Steig leitet nach Westen und quert die H‰nge zum Kaiserjochhaus. Dabei f¸hrt die stellenweise sehr schmale Route durch steiles, absch¸ssiges und felsiges Gel‰nde (zahlreiche versicherte Passagen) und stets ein wenig auf und ab. Die letzten Meter durch Wiesen ans Ziel.",
        "start": "Ansbacher H¸tte",
        "ziel": "Kaiserjochhaus",
        "auf": "520",
        "ab": "580",
        "hp": "2481",
        "grad": "schwierig",
        "km": "8,5",
        "stunden": "5",
        "einkehr": "Ansbacher H¸tte#Kaiserjochhaus",
        "track": "A23"
    },
    {
        "nr": "24",
        "titel": "Adlerweg-Etappe 24: Kaiserjochhaus ñ St. Christoph am Arlberg",
        "text": "Diese letzte Etappe am Nordtiroler Adlerweg f¸hrt vom Kaiserjochhaus nach St. Christoph am Arlberg. Die Route f¸hrt durch Almwiesen und Bergh‰nge, speziell zwischen Kaiserjochhaus und Leutkircher H¸tte sollte man Innehalten und dem Pfeifen der Murmeltiere lauschen. ",
        "info": "Vom Kaiserjochhaus auf dem Steig in Richtung Westen auf eine gr¸nbewachsene Bergkuppe steigen, Seilsicherungen helfen dabei. Weiter geht es in einen Kessel mit schˆnen Bergwiesen. Der Steig quert die Wiesenh‰nge und zieht auf den Sattel zwischen Schindlekopf und Bergleskopf hinauf. Vom Sattel hinunter in einen weiteren gr¸nen Kessel und durch die Geiﬂwasen (Wiesengel‰nde) quer hin¸ber nach Westen wandern. Am Ende der Geiﬂwasen ¸ber eine Kuppe und weiter hinunter zur Leutkircher H¸tte. Diese liegt auf 2.251 Meter am ˆstlichen Rand des weitl‰ufigen, schrofigen Almajurjochs. Der Steig ist bis hierher zumeist sehr lehmig, nun wird er fester. Von†der Leutkircher H¸tte westw‰rts vorbei am Almajurjoch zum Bacheregg. Hier gibt es eine Abzweigung Oberer und Unterer Hˆhenweg. Der Adlerweg folgt vorerst dem leichteren Unteren Hˆhenweg (links) durch steiles, felsdurchsetztes Gel‰nde†zum Kapallkopf (teils seilversichert). Nach langen, strengen Wintern und kaltem Fr¸hjahr h‰lt sich der Schnee hier lange in einer Rinne. Nun geht es ca. 50 Hˆhenmeter in Serpentinen hinauf zum Oberen Hˆhenweg und weiter Richtung Westen durch das ÑMatunì (Kessel) hinauf zum Matunjoch. Weiter zum Valfagehrjoch, dann vorbei an den Gipslˆchern (Dolinen) hinunter zur Ulmer H¸tte. Der Blick in Richtung Westen zur Schweizer Grenze offeriert hier grandios die Berge des R‰tikon: Zimba, Schesaplana, Drusenfluh, Sulzfluh Ö Nach einer Rast bei der Ulmer H¸tte biegt man links ab, hinunter Richtung Galzig, und wandert ¸ber gr¸ne Bergwiesen durch das Arlberg-Skigebiet zum Speicherteich, quert oberhalb der Talstation Schindlergratbahn und wechselt dann auf den Panoramaweg, der westlich vorbei am Senderturm Galzig bis zur Bergstation f¸hrt.  Anschlieﬂend auf dem Maienweg durch Latschenfelder zum Maiensee, an diesem rechts vorbei, die Transportstraﬂe rechts von der Br¸cke queren und dem kleinen Fuﬂweg zur St. Christoph Alm folgen. Von hier f¸hrt die Almstraﬂe bis zur Arlbergpass-Straﬂe, wo einen die letzten Schritte dieser schˆnen Schluss-Etappe des Adlerweges zum Arlberg Hospiz Hotel in St. Christoph bringen.",
        "start": "Kaiserjochhaus",
        "ziel": "St. Christoph am Arlberg",
        "auf": "950",
        "ab": "1450",
        "hp": "2553",
        "grad": "mittelschwierig",
        "km": "17,5",
        "stunden": "3",
        "einkehr": "Kaiserjochhaus#Leutkircher H¸tte#Ulmer H¸tte",
        "track": "A24"
    },
    {
        "nr": "O1",
        "titel": "Adlerweg-Etappe O1: Strˆden ñ Johannish¸tte",
        "text": "Die erste Etappe am Adlerweg in Osttirol f¸hrt von Strˆden in der N‰he der ber¸hmten Umbalf‰lle bis zur Johannish¸tte, der ‰ltesten H¸tte in den Ostalpen. Die Route f¸hrt hinauf zu gleiﬂenden Gletschern und vorbei an tosenden Wasserf‰llen und sprudelnden Gletscherb‰chen.",
        "info": "Ausgangspunkt ist der Parkplatz in Strˆden, von dort geht es nach der Br¸cke dem Maurerbach entlang hinauf zur Jausenstation Stoanalm auf 1.450 Meter. Auf der orografisch linken Bachseite f¸hrt der Fahrweg zur Talstation der Materialseilbahn. Weiter auf einem Steig eine l‰rchenbewachsene Talstufe empor. Nach ca. zwei Dutzend Steigkehren gelangt man hinauf zur Gˆriacher Ochsnerh¸tte (1.948 Meter). Weiter f¸hrt der Steig, noch immer in Bachn‰he, ¸ber drei sanfte Steigungen ins Vorfeld der gletscherbedeckten Venedigerberge und zur Br¸cke bei der oberen Ochsnerh¸tte am Maurerbach. Der kraftvolle Gletscherbach trennt die Gˆriacher von der westlich gelegenen Maurer Alpe. Nun geht es bereits in den Schlusshang hinauf zur Essener-Rostocker H¸tte, im Mor‰nengebiet des inzwischen weit zur¸ckgezogenen Simonykees¥. Nach einer verdienten Pause wandert man von der Essener-Rostocker H¸tte ¸ber den Schweriner Weg weiter. In Kehren ¸berwindet er eine Bergflanke und quert nach ca. einer Stunde Gehzeit den S¸dwest-Hang des Kleinen Geigers. Nun geht es ¸ber eiszeitliche Schleifspuren und weit gestreute Schuttfelder Richtung T¸rml mit seinem hellen roten Fels. An seinem Fuﬂ liegt das T¸rmljoch (2.772 Meter). ÷stlich davon f¸hrt der in Schleifen angelegte Steig durch Schneemulden und ¸ber Schuttbˆden und in weiterer Folge den Dorferkamm-Osthang hinab. Ca. º Stunde sp‰ter schwenkt man, einige Rinnsale ¸bersteigend, nach Nordosten. Dann bew‰ltigt der Steig noch eine dem Gel‰nde angepasste Wende in Richtung S¸den ¸ber einen Berghang, der zum Dorfer Bach hinunterf¸hrt, wo man schˆne Felsschliffe bewundern kann. Schlieﬂlich geht es am Gedenkkreuz vorbei und ¸ber den Zettalunitzbach das letzte St¸ck zur urigen und ger‰umigen Johannish¸tte (2.121 Meter). Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Strˆden",
        "ziel": "Johannish¸tte",
        "auf": "1430",
        "ab": "730",
        "hp": "2773",
        "grad": "mittelschwierig",
        "km": "13",
        "stunden": "6,5",
        "einkehr": "Stoanalm#Essener- und Rostocker H¸tte#Johannish¸tte",
        "track": "O1"
    },
    {
        "nr": "O2",
        "titel": "Adlerweg-Etappe O2: Johannish¸tte ñ Eisseeh¸tte",
        "text": "Entlang dieser Adlerweg-Etappe begeistern tolle Ausblick auf die benachtbarten Gletscherberge. Die Route f¸hrt von der Johannish¸tte ¸ber den Sajat-Hˆhenweg und vorbei an der Sajath¸tte zur Eisseeh¸tte. ",
        "info": "Von der Johannish¸tte f¸hrt der Venediger Hˆhenweg bzw. Adlerweg Richtung Osten und erreicht bald auf einem Kehrensteig die scharf hervortretende Zopetkante. Danach geht es weiter durch steiles Bergwiesengel‰nde, wobei man vereinzelt Steinm‰nnchen zu Gesicht bekommt. Ab und zu lohnt sich ein Innehalten, um einen Blick auf die gleiﬂenden Gletscher des Groﬂvenedigers zur¸ckzuwerfen. Nach ca. einer Stunde ˆffnet sich ein kleines Hochtal, man h‰lt sich dort beim Wegweiser s¸dlich Richtung ÑSajatscharteì. Nach der Querung eines Blockfeldes gelangt man in hochalpines Gel‰nde mit Steiganlage. Relativ breit und sicher, teilweise mit Stahlseilen versehen, quert der Weg die Steilflanke und f¸hrt zur Schernersschlucht, ehe er ¸ber einige Kehren im felsigen Gel‰nde die Sajatscharte erreicht. Von hier dauert der Abstieg zur Sajath¸tte ca. Ω Stunde. Dabei geht es zuerst eine Schuttrinne hinunter, dann weiter auf sandigem Boden am Fuﬂ der Roten S‰ule, bevor man ¸ber einen Rasenhang zur Sajath¸tte (2.575 Meter) gelangt. Eine willkommene Zwischenstation zur kulinarischen St‰rkung, bevor man auf dem Pr‰gratner-Hˆhenweg in Richtung Eisseeh¸tte weitermarschiert. Dieser Steig verbindet die Sajath¸tte mit der Eisseeh¸tte, ohne dass man dazu ins Tal absteigen muss. Man verl‰sst die Sajath¸tte in Richtung Osten und umschreitet beim sogenannten ÑFensterì den Vorderen Sajatkopf auf dessen auslaufendem S¸dostgrat. Dort wendet sich der Steig Richtung Norden. Die zu querenden Steilrinnen sind wieder mit einer Steiganlage gut begehbar gemacht. Auch ein Hanganstieg ist durch bequeme Kehren entsch‰rft. Weiter geht es durchs innere Timmeltal  bis zur Ortsbezeichnung ÑHinteres Wiesachì, wo sich das Gel‰nde wieder gem‰ﬂigter zeigt. Nun noch das letzte St¸ck ¸ber den Timmelbach zur gem¸tlichen Eisseeh¸tte (2.521 Meter). Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Johannish¸tte",
        "ziel": "Eisseeh¸tte",
        "auf": "1020",
        "ab": "620",
        "hp": "2788",
        "grad": "mittelschwierig",
        "km": "10",
        "stunden": "6",
        "einkehr": "Neue Sajath¸tte#Eisseeh¸tte",
        "track": "O2"
    },
    {
        "nr": "O3",
        "titel": "Adlerweg-Etappe O3: Eisseeh¸tte ñ  Bonn-Matreier-H¸tte",
        "text": "Gipfelerlebnisse noch und noch, selbst wenn man die Gipfel nicht erklimmt, sondern auf dem Venediger Hˆhenweg daran vorbeiwandert warten auf dieser Etappe von der Eisseeh¸tte bis zur Bonn-Matreier-H¸tte.",
        "info": "Von der Eisseeh¸tte steigt man ein kurzes St¸ck zu den Wegtafeln des Venediger Hˆhenwegs hinab, wo dieser in den linken ˆstlichen Hangbereich des Timmeltals lenkt. Die ‹berschreitung des auslaufenden S¸dwestkammes vom Hexenkopf ist leicht zu bew‰ltigen, gleich darauf ¸berwindet man den westlich auslaufenden Felsgrat des Hohen Eicham. Der bisher leicht und nahezu eben verlaufende Steig wird nun sch‰rfer, denn er stˆﬂt auf den Westausl‰ufer der Wunwand, mit der man eine Zeitlang auf Tuchf¸hlung bleibt. Steinerne Treppen dienen der Sicherheit, auch ein Stahlseil ist auf einem kurzen Wegst¸ck gespannt. Es geht noch einige Kehren hinauf, man quert eine Wiesenflanke, etwa einen Kilometer bis zum Wunwand-S¸dwestgrat. In diesem Bereich gibt es eine Abzweigmˆglichkeit zur Wallhornalm im Timmeltal, der Hˆhenweg f¸hrt aber weiter ¸ber eine Wiesenflanke s¸dlich der Wunwand bis zum ausklingenden S¸dgrat der Wunspitze. Dort steigt man ca. Ω Stunde zu einer Felsnische hinauf. Ein St¸ck hˆher teilt sich der Steig und man kˆnnte nach links zur Oberen und rechts zur Unteren Wunalm gelangen. Die Route des Venediger Hˆhenwegs verl‰uft nun hoch ¸ber dem Virgental, zum Teil unter den Bruchst¸cken eines alten Felssturzes hindurch und f¸hrt schlieﬂlich auf den Eselsr¸cken, der den Zugang zum Groﬂen Niltal ˆffnet. 15 enge Kehren f¸hren von der Anhˆhe durch eine schmale Rasenrinne hinab auf den Sandboden. Dort ein paar Schritte ¸ber den schm‰chtigen Abfluss aus dem Nilkees. Das Etappenziel, die Bonn-Matreier-H¸tte, ist dabei l‰ngst schon in Sicht. Auf einem guten Steig und ¸ber in den Fels gehauene Steinstufen gelangt man in den Bereich des stattlichen, schindelverkleideten Schutzhauses, das beste Verpflegung offeriert. Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Eisseeh¸tte",
        "ziel": "Bonn-Matreier-H¸tte",
        "auf": "600",
        "ab": "370",
        "hp": "2750",
        "grad": "mittelschwierig",
        "km": "7",
        "stunden": "3,5",
        "einkehr": "Bonn-Matreier-H¸tte",
        "track": "O3"
    },
    {
        "nr": "O4",
        "titel": "Adlerweg-Etappe O4: Bonn-Matreier H¸tte  ñ  Badener H¸tte",
        "text": "Auf dieser schwierigen, vierten Adlerweg-Etappe in Osttirol geht es von der Bonn-Matreier-H¸tte bis zur Badener H¸tte. Dabei passiert man die Sch‰rfere Galtenscharte und arbeitet sich Schritt f¸r Schritt immer weiter zum Hoheitsgebiet des Groﬂglockners vor.",
        "info": "Ein St¸ck oberhalb der Bonn-Matreier H¸tte (ca. 8-10 Minuten Gehzeit), zweigt bei Wegtafeln der Steig nach rechts ab. Man durchschreitet einen steinigen Bergtrog und erreicht schlieﬂlich die schr‰gen Felst¸rme der K‰lberscharte (2.791 Meter). Auf beiden Seiten der Scharte erleichtern Treppen und Stahlseile den ‹bergang ins Kleine Niltal, so bezwingt man auch den Aufstieg zur hˆher gelegenen Galtenscharte relativ problemlos. Nun erfolgt der steile, fordernde Abstieg hinunter zum Mailfroﬂnitzbach, obwohl man die 600 Hˆhenmeter sp‰ter wieder wett machen muss. Der obere Teil des Steilst¸ckes ist stahlseilversichert, im Mittelst¸ck erwartet einen oft auch im Sommer ein hartn‰ckiges, steiles Schneefeld. Wenn man Gl¸ck hat und der Wegabschnitt schneefrei ist, verl‰uft der Steig durchgehend. Weiter unten wird das Gel‰nde flacher, der Abstieg endet bei der Br¸cke ¸ber den Mailfroﬂnitzbach. Etwa 40 Meter unterhalb der Br¸cke befindet sich die Fortsetzung des Steiges. Hoch ¸ber dem Froﬂnitztal quert man nun die gr¸nen H‰nge der Hohen Achsel von S¸den nach Norden und passiert dabei landschaftlich sehr abwechslungsreiche Teilst¸cke. Kurze Stellen sind stahlseilversichert, man kommt an zahlreichen kleinen B‰chen vorbei. Auf der sogenannten Achsel befindet sich ein grasumwachsener, von einer Mor‰ne abgedichteter T¸mpel. Hier verbindet sich der Venediger Hˆhenweg mit dem Talweg. Es geht weiter in Richtung ÑBadener H¸tteì, wobei man eng hintereinander gereihte Mor‰nen und schlieﬂlich die Br¸cke am Froﬂnitzbach ¸berschreitet. Es folgen einige R¸cken und Mulden, die den Schneeh¸hnern Schutz bieten. Schlieﬂlich gelangt man zur Seitenmor‰ne des Frosnitzkees¥, dort h‰lt man sich rechts und wandert weiter, bis man das Etappenziel, die Badener H¸tte (2.608 Meter) am Groﬂvenediger, erreicht. Wegbeschreibungen siehe auch ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Bonn-Matreier-H¸tte",
        "ziel": "Badener H¸tte",
        "auf": "800",
        "ab": "950",
        "hp": "2872",
        "grad": "schwarz",
        "km": "10",
        "stunden": "5",
        "einkehr": "Badener H¸tte",
        "track": "O4"
    },
    {
        "nr": "O5",
        "titel": "Adlerweg-Etappe O5: Badener H¸tte  ñ  Matreier Tauernhaus",
        "text": "Ein wunderbares Gletscherpanorama wartet entlang dieser Adlerweg-Etappe in Osttirol. ‹ber den Venediger Hˆhenweg f¸hrt die Route nach Osten zum Venedigerhaus von Innergschlˆss und schlieﬂlich weiter bis zum Etappenziel, dem Matreier Tauernhaus.",
        "info": "Von der Badener H¸tte (2.608 Meter) wandert man zuerst ¸ber den Venediger Hˆhenweg bzw. Adlerweg (hier auch Badener Weg) nordw‰rts ca. eine Stunde hinauf zum Lˆbbentˆrl (2.770 Meter). Dabei sind einige felsdurchzogene Rinnen und kleine Schluchten seilversichert.  ‹ber eine kurze Halde steigt man weiter zum Lˆbbentˆrl hinan, wo im Schutz eines Felsens ein Kreuz und eine Gedenktafel stehen. Von nun an geht es steil bergab. Der nordseitige Abstieg mit kurzen Seilstellen f¸hrt auf Fels-Rasen-R¸cken und Altschnee hinunter zur Seitenmor‰ne des Schlatenkees¥. Auf dieser Mor‰ne steigt man weiter ab. Am Unteren Keesboden gibt es einen ‹bergang zur Alten Prager H¸tte (nicht bewirtschaftet),  hier kann man auch zum faszinierenden Gletscherschaupfad ÑInnergschlˆssì abzweigen. Der Venediger Hˆhenweg passiert den Salzbodensee (2.731 Meter), in dem sich Hoher Zaun und Schwarze Wand spiegeln. Nˆrdlich des gletscherweiﬂen Gschlˆssbaches wendet sich der Weg scharf nach Osten. Im gletschernahen, gut gef¸hrten Venedigerhaus (1.689 Meter) l‰sst sich eine gem¸tliche Rast einschieben. Entlang des Gschlˆssbaches geht es dann weiter talausw‰rts, zwischen den Almen von Inner- und Auﬂergschlˆss bietet sich ein Innehalten bei der alten Felsenkapelle an. Eine Einkehr weltlicher Art ist im Berghaus Auﬂergschlˆss (1.700 Meter) empfehlenswert. Das Tal weitet sich nun. Von Gschlˆss geht es noch ca. eine Stunde sanft ¸ber nicht einmal 200 Hˆhenmeter bergab zum Matreier Tauernhaus (1.512 Meter), wo man nach den langen fordernden Abstiegen dieser Etappe vermutlich etwas knieweich ankommt. Hier kann man sich ausruhen, feine regionale Schmankerln genieﬂen und komfortabel ¸bernachten. Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Badener H¸tte",
        "ziel": "Matreier Tauernhaus",
        "auf": "450",
        "ab": "1550",
        "hp": "2768",
        "grad": "schwarz",
        "km": "14",
        "stunden": "5,5",
        "einkehr": "Venedigerhaus#Matreier Tauernhaus",
        "track": "O5"
    },
    {
        "nr": "O6",
        "titel": "Adlerweg-Etappe O6: Matrei in Osttirol ñ Sudetendeutsche H¸tte",
        "text": "Ausgehend vom Matreier Tauernhaus verl‰uft diese Etappe am Osttiroler Adlerweg bis zur Sudetendeutschen H¸tte. Auf der Route gilt es ziemlich viele kraftraubende Hˆhenmeter zu absolvieren, die M¸hen werden mit faszinierenden Ausblicken auf die Lasˆrlinggruppe belohnt.",
        "info": "Am besten startet man diese Etappe beim Parkplatz im Weiler Glanz, dann spart man sich zwei Stunden Anmarsch. Von Matrei in Osttirol kann man mit dem PKW (Taxidienst auf Anfrage) in 20 Minuten dorthin gelangen. All jene, die auch diesen ersten Streckenabschnitt zu Fuﬂ bew‰ltigen wollen, gelangen ¸ber den wenig befahrenen Fahrweg von Matrei ¸ber Hinterburg zum Parkplatz.†Vom Parkplatz in Glanz kommt man in 1 Ω  bis 2 Stunden zur ƒuﬂeren Steiner Alm und in weiteren 2 bis 2 Ω Stunden zur Sudetendeutschen H¸tte. Der Steig f¸hrt groﬂteils durch einen Wald mit uralten L‰rchen, vorbei an der Kˆfler-Almh¸tte (Privatalm). Im Bereich der Ranzeralm quert man zweimal den Fahrweg. Etwas oberhalb der Lackner-Almh¸tte beginnt ein Karrenweg, der an einer Quelle vorbeif¸hrt, ehe er von Osten nach Westen die Edelweiﬂwiese durchzieht. Wer nicht durch den Wald wandern mˆchte, kann auch vom Parkplatz Glanz entlang der Forststraﬂe bis zum Beginn der Edelweiﬂwiese gehen. Nach einer Felskante f‰llt der durch ein Gel‰nder gesch¸tzte Steig in den lichten L‰rchenwald leicht ab. ‹ber den Steinerbach gelangt man zu den Almh¸tten der ƒuﬂeren Steiner Alm (1.914 Meter), von der ƒuﬂeren Steiner Alm geht es in der flachen Trogtalsohle nordˆstlich weiter in Richtung Talschluss. Kleine L‰rchenhaine und gewaltige Gr¸nschieferblˆcke pr‰gen diesen romantischen Wegabschnitt. Am Ende des Talschlusses f¸hrt eine Materialseilbahn zur Sudetendeutschen H¸tte, hier befand sich fr¸her eine Fˆrderst‰tte des Eisenerz-Bergbaus, deshalb wird der Talwinkel als ÑSchmelzh¸tteì bezeichnet. Der Steig zur Sudetendeutschen H¸tte f¸hrt zuerst nah am Steinerbach hinauf, dann windet er sich in Kehren ¸ber die Wiesenh‰nge empor, wobei man den Nussingkogel zur linken und die Bretterwandspitze zur rechten Seite hat. Schlieﬂlich wird das Gel‰nde mit seinen von den Gletschern geformten Kuppen etwas flacher und schon befindet man sich im Nahbereich der ger‰umigen Sudetendeutschen H¸tte (2.650 Meter) inmitten der Granatspitzgruppe.†Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair. †",
        "start": "Matreier Tauernhaus",
        "ziel": "Sudetendeutsche H¸tte",
        "auf": "1250",
        "ab": "100",
        "hp": "2656",
        "grad": "mittelschwierig",
        "km": "8",
        "stunden": "4",
        "einkehr": "Steiner Alm#Sudetendeutsche H¸tte",
        "track": "O6"
    },
    {
        "nr": "O7",
        "titel": "Adlerweg-Etappe O7: Sudetendeutsche H¸tte  ñ  Kalser Tauernhaus",
        "text": "Die Granatspitzgruppe im zentralen Bereich der Hohen Tauern f¸gt sich in das beeindruckende Bergpanorama dieser Adlerweg-Etappe, die von der Sudetendeutschen H¸tte zum Kalser Tauernhaus f¸hrt. Dabei kommt man auf dem Teilabschnitt der ÑGlockner-Rundeì dem Groﬂglockner immer n‰her.",
        "info": "Von der Sudetendeutschen H¸tte wandert man am Gedenkkreuz und am h¸ttennahen kleinen Bergsee vorbei ¸ber Rasenr¸cken und bemooste Mulden hinauf ins Abflussgebiet des Gradˆtzkees¥, wo sich ebenfalls ein See angestaut hat und m‰chtige Mor‰nen die Landschaft pr‰gen. Schlieﬂlich erreicht man den Gradˆtzsattel (2.826 Meter), danach geht es hinunter, dem sogenannten Bloipalfen (2.684 Meter) entgegen. Anschlieﬂend weiter bergab ¸ber ein Wiesenst¸ck und klammartig gelagerte Felsen. Auf ca. 2.500 Meter Hˆhe zweigt der Silesiaweg links ab. Er f¸hrt in wenigen Minuten Gehzeit auf die felsige Muntanitzschneid mit grandioser Aussicht, auf dem Adlerweg bleibend h‰lt man sich jedoch rechts und erreicht schlieﬂlich den Muntanitzbach, der bei starker Wasserf¸hrung nicht so einfach - vor allem nicht trockenen Fuﬂes - zu ¸berwinden ist. Ein St¸ck oberhalb des Gebietes der Ochsenalm umschreitet man den auslagernden R¸cken der Muntanitzschneid. Der Weg ist hier gut ausgebaut, im unteren Teil vollf¸hrt er einen kleinen Knick und weist eine felsige Stelle auf. In weiterer Folge geht es ¸ber Wiesenh‰nge hinunter und man durchstreift in nˆrdlicher Richtung ein kleines Zirbenw‰ldchen. Man gelangt schlieﬂlich zu einer Hinweistafel zur Br¸cke am Stotzbach mit zuflieﬂendem Loamesbach. Bei der etwas tiefer stehenden Wegtafel w‰hlt man den Abstieg, bez. 514 A, zum Kalser Tauernhaus. Auf zahlreichen engen Kehren wandert man nun am Wilhelm-Ernst-Weg zwischen Erlen, Eschen und L‰rchen im Zickzack talw‰rts, an der Nationalpark-Aussichtskanzel vorbei, wo ein Wasserfall des Stotzbaches ¸ber eine von eiszeitlichen Gletschern geschaffene Trogschulter in die Tiefe wirbelt. Schlieﬂlich geht es ¸ber den Dorferbach zum Etappenziel, dem gem¸tlich eingerichteten Kalser Tauernhaus (1.755 Meter). Dieses befindet sich im hinteren Teil des Dorfertales, nur ein kleines St¸ck unterhalb jener Stelle, wo der Stotzbach in den Dorferbach m¸ndet. Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Sudetendeutsche H¸tte",
        "ziel": "Kalser Tauernhaus",
        "auf": "300",
        "ab": "1200",
        "hp": "2828",
        "grad": "mittelschwierig",
        "km": "8",
        "stunden": "4",
        "einkehr": "Kalser Tauernhaus",
        "track": "O7"
    },
    {
        "nr": "O8",
        "titel": "Adlerweg-Etappe O8: Kalser Tauernhaus - St¸dlh¸tte",
        "text": "Zollspitze, S‰ulspitze, Bretterspitze, Kristallspitze, Kreuzwandspitze: Entlang dieser Adlerweg-Etappe zur St¸dlh¸tte am Fuﬂe des Groﬂglockners gr¸ﬂen zahlreiche markante Gipfel.",
        "info": "Vom Kalser Tauernhaus verl‰uft der Adlerweg bis zur Moaalm st‰ndig in Richtung S¸den durch das liebliche Dorfertal auf einem breiten Almweg leicht abw‰rts. Man passiert dabei u.a. die Kalseralmen der Rumesoi-und Schˆnebene. Bald nach der Jausenstation Bergeralm zweigt bei der Moaebene links der Weg Nr. 40 ¸ber einen Trittsicherheit erfordernden Steig (Ñdie Stiegeì), hinauf zur Moaalm (1.793 Meter), oberhalb von Kals. Weiter abw‰rts ¸ber die Moaalmstraﬂe bis zur Br¸cke am Teischnitzbach, wo nach etwa 70 Meter bei einer Zaunl¸cke eine Wegtafel ins Teischnitztal weist. Dieses ist noch sehr urspr¸nglich und begeistert ebenfalls mit landschaftlicher Schˆnheit. Von dort f¸hrt ein Almweg auf der l‰rchenbewachsenen rechten Talseite empor. Es gibt aber auch einen abk¸rzenden Steig, der den Almweg mehrmals kreuzt. Er passiert beim Maurigen Trog (2.101 Meter), die schmale, 800 Meter lange Felsklamm (2.075 Meter). Am Eingang in den Hochtaltrog der Teischnitz-Ebene (Br¸cke) zeigt ein Wegweiser an, dass hier der zur St¸dlh¸tte f¸hrende Steig rechts in die steilen Bergh‰nge abzweigt. Bald blickt man auf den rauschenden Teischnitzbach hinunter und sieht die Eist¸rme des Teischnitzkees aufblitzen. Es gilt noch einige steile Wiesenh‰nge, Rippen und Rinnen zu ¸berwinden, ehe man sich abschlieﬂend ¸ber Schutt und Steinblˆcke von S¸den der St¸dlh¸tte n‰hert (2.802 Meter). Sie steht am Fuﬂ vom Groﬂglockner, das Berg- und Gletscherpanorama ist dementsprechend grandios. Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "Kalser Tauernhaus",
        "ziel": "St¸dlh¸tte",
        "auf": "1440",
        "ab": "400",
        "hp": "2802",
        "grad": "mittelschwierig",
        "km": "14",
        "stunden": "6,5",
        "einkehr": "Bergeralm#Moaalm#St¸dlh¸tte",
        "track": "O8"
    },
    {
        "nr": "O9",
        "titel": "Adlerweg-Etappe O9: St¸dlh¸tte ñ Lucknerhaus",
        "text": "Die letzte Etappe am Osttiroler Adlerweg f¸hrt von der St¸dlh¸tte am Fuﬂe des Groﬂglockners zum Lucknerhaus. Hier endet der Adlerweg und die Kalser Glocknerstraﬂe schl‰ngelt sich von dort abw‰rts ins Tal.",
        "info": "Von der St¸dlh¸tte auf der Fanotscharte (2.802 Meter) steigt man in nˆrdlicher Richtung f¸nf Minuten bergan, orientiert sich dann nach Osten am Wegweiser Pfortscharte, Salmh¸tte, Glorer H¸tte, ¸ber den Weg AV 713 in Richtung S¸den, S¸dosten. Dieser verl‰uft direkt unterhalb der Mor‰nenfelder des Kˆdnitzkees¥und m¸ndet weit oberhalb der sogenannten Viehbˆden in den Johann-St¸dl-Weg (AV 702 B). Der zun‰chst gut ausgebaute Weg zieht nun hinauf durch Wiesenh‰nge, sp‰ter wieder seilversichert nach oben. Jetzt hinein in das Schuttkar und darin weiter durch das Kar aufw‰rts. Bei einer Steiggabelung im Kar nicht rechts in die Felsen, sondern weiter Richtung Salmh¸tte durch das Kar aufw‰rts. Der Steig leitet in dieser Passage in kurzen Serpentinen durch Schutt und Gerˆll, aber mit gutem Untergrund. Steil geht es hinauf zur Pfortscharte. Auf der anderen Seite ein kurzes St¸ck in ‰hnlichem Gel‰nde abw‰rts, bei der Steiggabelung Richtung ÑGlorer H¸tteì orientieren. Von hier geht es am Luckner Weg Richtung S¸den, auf gr¸nen, welligen Bergmatten u.a. am Oberen Glatzsee vorbei und man erreicht nach einiger Zeit die Glorer H¸tte am Berger Tˆrl (2.651 Meter). Im breiten, von Wiesenh‰ngen gepr‰gten Bergtal finden sich Stirnmor‰nen ehemaliger Gletschert‰tigkeit, die bis in die Mulde mit dem Glatzbach reichen. Nach der Glorer H¸tte verl‰uft der Weg parallel zur Materialseilbahn auf zum Teil erdigem Steig und ¸ber einige kleinere B‰chlein weiter talw‰rts zwischen Bergwiesen hinunter, wo man sich zum Schutz der Natur auf dem Steig halten sollte. Schlieﬂlich m¸ndet der Steig in einen breiten Weg, der zum Lucknerhaus f¸hrt. Etappenziel und Ende des Adlerweges Osttirol! Oder der schˆne Beginn, wenn man ihn von dieser Seite aus in Angriff nimmt. Wegbeschreibungen siehe auch: ÑOsttiroler Wanderbuchì von Walter Mair.",
        "start": "St¸dlh¸tte",
        "ziel": "Lucknerhaus",
        "auf": "450",
        "ab": "1330",
        "hp": "2824",
        "grad": "mittelschwierig",
        "km": "11",
        "stunden": "5,5",
        "einkehr": "Glorer H¸tte#Luchknerhaus",
        "track": "O9"
    }
]